// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// doram_gk15_panel_cpp
Rcpp::List doram_gk15_panel_cpp(const double a, const double b, const double y, const double N, const double eta, const double sigma, const double mode, const double p_mode, const double mode_residual);
RcppExport SEXP _DORAM_doram_gk15_panel_cpp(SEXP aSEXP, SEXP bSEXP, SEXP ySEXP, SEXP NSEXP, SEXP etaSEXP, SEXP sigmaSEXP, SEXP modeSEXP, SEXP p_modeSEXP, SEXP mode_residualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type N(NSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< const double >::type p_mode(p_modeSEXP);
    Rcpp::traits::input_parameter< const double >::type mode_residual(mode_residualSEXP);
    rcpp_result_gen = Rcpp::wrap(doram_gk15_panel_cpp(a, b, y, N, eta, sigma, mode, p_mode, mode_residual));
    return rcpp_result_gen;
END_RCPP
}
// doram_integrate_moments_cpp
Rcpp::List doram_integrate_moments_cpp(const double y, const double N, const double eta, const double sigma, const double mode, const double p_mode, const double mode_residual, const double local_scale, const double relative_tolerance, const double radius, const int maximum_panels, Rcpp::NumericVector tail_error);
RcppExport SEXP _DORAM_doram_integrate_moments_cpp(SEXP ySEXP, SEXP NSEXP, SEXP etaSEXP, SEXP sigmaSEXP, SEXP modeSEXP, SEXP p_modeSEXP, SEXP mode_residualSEXP, SEXP local_scaleSEXP, SEXP relative_toleranceSEXP, SEXP radiusSEXP, SEXP maximum_panelsSEXP, SEXP tail_errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const double >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type N(NSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< const double >::type p_mode(p_modeSEXP);
    Rcpp::traits::input_parameter< const double >::type mode_residual(mode_residualSEXP);
    Rcpp::traits::input_parameter< const double >::type local_scale(local_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type relative_tolerance(relative_toleranceSEXP);
    Rcpp::traits::input_parameter< const double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< const int >::type maximum_panels(maximum_panelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tail_error(tail_errorSEXP);
    rcpp_result_gen = Rcpp::wrap(doram_integrate_moments_cpp(y, N, eta, sigma, mode, p_mode, mode_residual, local_scale, relative_tolerance, radius, maximum_panels, tail_error));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DORAM_doram_gk15_panel_cpp", (DL_FUNC) &_DORAM_doram_gk15_panel_cpp, 9},
    {"_DORAM_doram_integrate_moments_cpp", (DL_FUNC) &_DORAM_doram_integrate_moments_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_DORAM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
