#!/usr/bin/env Rscript

# ==============================================================================
# DASRA structural-absence simulation against observed-prevalence methods
# ==============================================================================
#
# Primary comparison:
#   1. A structural-absence difference with matched expected observed prevalence.
#   2. An abundance-induced observed-prevalence difference with no structural-
#      absence difference.
#
# Conditional on ecological presence, the target taxon follows a beta
# distribution with a fixed first shape parameter. Its mean changes across
# groups while its logit-scale dispersion remains approximately stable. Read
# counts are then generated by multinomial sampling. This beta-multinomial
# mechanism differs from DASRA's logistic-normal working model without
# introducing an unintended group difference in conditional-present dispersion.
#
# All methods are evaluated with raw, unadjusted p-values at ALPHA. Because the
# methods target different null hypotheses, the output uses the neutral term
# "empirical rejection rate" rather than calling every curve power.
#
# Direct run:
#   Rscript dasra_structural_vs_prevalence_simulation_v2.R
#
# Optional environment variables:
#   DASRA_SIM_REPS=200
#   DASRA_SIM_N_PER_GROUP=200
#   DASRA_SIM_CORES=8
#   DASRA_SIM_OUTDIR=/path/to/output
#   DASRA_SIM_RESUME=true
#
# Required packages:
#   DASRA, ZINQ, maaslin3, logistf, ggplot2, dplyr
#
# Installation examples:
#   remotes::install_github("wdl2459/ZINQ-v2")
#   BiocManager::install("maaslin3")
#
# ==============================================================================

options(stringsAsFactors = FALSE)
Sys.setenv(
    OMP_NUM_THREADS = "1",
    OPENBLAS_NUM_THREADS = "1",
    MKL_NUM_THREADS = "1",
    VECLIB_MAXIMUM_THREADS = "1"
)

physical_cores <- suppressWarnings(parallel::detectCores(logical = FALSE))
if (!is.finite(physical_cores) || physical_cores < 1L) physical_cores <- 1L
requested_cores <- suppressWarnings(as.integer(Sys.getenv(
    "DASRA_SIM_CORES", as.character(min(8L, physical_cores))
)))
if (!is.finite(requested_cores)) requested_cores <- 1L

env_flag <- function(name, default = TRUE) {
    value <- tolower(trimws(Sys.getenv(name, if (default) "true" else "false")))
    if (value %in% c("true", "1", "yes", "y")) return(TRUE)
    if (value %in% c("false", "0", "no", "n")) return(FALSE)
    stop(sprintf("%s must be true or false.", name), call. = FALSE)
}

CONFIG <- list(
    script_version = "2026-08-17-v3-scenario-specific-baselines",
    n_rep = suppressWarnings(as.integer(Sys.getenv("DASRA_SIM_REPS", "200"))),
    n_per_group = suppressWarnings(as.integer(Sys.getenv(
        "DASRA_SIM_N_PER_GROUP", "200"
    ))),
    n_cores = max(1L, min(8L, requested_cores)),
    alpha = 0.05,
    base_seed = 20260817L,
    output_dir = Sys.getenv(
        "DASRA_SIM_OUTDIR",
        file.path(getwd(), "dasra_structural_vs_prevalence_simulation_v3")
    ),
    resume = env_flag("DASRA_SIM_RESUME", TRUE),
    base_structural_absence = 0.30,
    structural_base_relative_abundance = 8.0e-5,
    detectability_base_relative_abundance = 1.5e-4,
    beta_shape1 = 3.0,
    structural_log_odds_effects = c(0, 0.40, 0.80, 1.20, 1.50),
    detectability_log_abundance_effects = c(0, 0.20, 0.40, 0.60, 0.80),
    include_concordant_structural_scenario = FALSE,
    depth_median = 8000,
    depth_sdlog = 0.45,
    depth_min = 1500L,
    depth_max = 40000L,
    n_background_taxa = 25L,
    background_dirichlet_concentration = 75,
    target_probability_guard = 0.25,
    maaslin3_keep_abundance_warning = TRUE,
    zinq_quantile_tau = 0.50
)

validate_config <- function(config) {
    if (!is.finite(config$n_rep) || config$n_rep < 1L) {
        stop("CONFIG$n_rep must be a positive integer.", call. = FALSE)
    }
    if (!is.finite(config$n_per_group) || config$n_per_group < 20L) {
        stop("CONFIG$n_per_group must be at least 20.", call. = FALSE)
    }
    if (!is.finite(config$alpha) || config$alpha <= 0 || config$alpha >= 1) {
        stop("CONFIG$alpha must lie strictly between 0 and 1.", call. = FALSE)
    }
    if (config$base_structural_absence <= 0 ||
        config$base_structural_absence >= 1) {
        stop("The baseline structural-absence probability must lie in (0, 1).",
             call. = FALSE)
    }
    if (!is.finite(config$structural_base_relative_abundance) ||
        config$structural_base_relative_abundance <= 0 ||
        config$structural_base_relative_abundance >= 1) {
        stop(
            "The structural-scenario baseline relative abundance must lie in (0, 1).",
            call. = FALSE
        )
    }
    if (!is.finite(config$detectability_base_relative_abundance) ||
        config$detectability_base_relative_abundance <= 0 ||
        config$detectability_base_relative_abundance >= 1) {
        stop(
            "The detectability-scenario baseline relative abundance must lie in (0, 1).",
            call. = FALSE
        )
    }
    if (!is.finite(config$beta_shape1) || config$beta_shape1 <= 0) {
        stop("The fixed first beta shape parameter must be positive.",
             call. = FALSE)
    }
    invisible(config)
}

check_packages <- function() {
    required <- c("ZINQ", "maaslin3", "logistf", "ggplot2", "dplyr")
    missing <- required[!vapply(required, requireNamespace, logical(1),
                               quietly = TRUE)]
    dasra_namespace <- if (requireNamespace("DASRA", quietly = TRUE)) {
        "DASRA"
    } else if (requireNamespace("dasra", quietly = TRUE)) {
        "dasra"
    } else {
        NA_character_
    }
    if (is.na(dasra_namespace)) {
        missing <- c(missing, "DASRA")
    }
    if (length(missing)) {
        stop(
            paste0(
                "Missing required package(s): ", paste(unique(missing), collapse = ", "),
                ".\nInstall ZINQ with remotes::install_github(\"wdl2459/ZINQ-v2\"), ",
                "MaAsLin 3 with BiocManager::install(\"maaslin3\"), and install ",
                "the local DASRA package before running this script."
            ),
            call. = FALSE
        )
    }
    fingerprint_names <- c(
        "dasra",
        "zt_fit_beta",
        "zt_fit_alpha",
        "zt_count_structural_test"
    )
    list(
        dasra_namespace = dasra_namespace,
        dasra = getExportedValue(dasra_namespace, "dasra"),
        dasra_fingerprint = function_fingerprint(
            dasra_namespace, fingerprint_names
        )
    )
}

collapse_conditions <- function(x) {
    x <- unique(trimws(x[nzchar(trimws(x))]))
    if (!length(x)) NA_character_ else paste(x, collapse = " | ")
}

text_md5 <- function(text) {
    path <- tempfile("dasra_sim_fingerprint_")
    on.exit(unlink(path), add = TRUE)
    writeLines(enc2utf8(as.character(text)), path, useBytes = TRUE)
    unname(tools::md5sum(path))
}

function_fingerprint <- function(namespace, function_names) {
    namespace_environment <- asNamespace(namespace)
    available <- function_names[vapply(
        function_names,
        exists,
        logical(1),
        envir = namespace_environment,
        inherits = FALSE
    )]
    if (!length(available)) {
        stop("No DASRA functions were available for fingerprinting.",
             call. = FALSE)
    }
    pieces <- vapply(available, function(name) {
        fun <- get(name, envir = namespace_environment, inherits = FALSE)
        paste(
            name,
            paste(deparse(formals(fun), width.cutoff = 500L), collapse = "\n"),
            paste(deparse(body(fun), width.cutoff = 500L), collapse = "\n"),
            sep = "\n"
        )
    }, character(1))
    text_md5(pieces)
}

object_fingerprint <- function(object) {
    path <- tempfile("dasra_sim_record_")
    on.exit(unlink(path), add = TRUE)
    saveRDS(object, path, version = 3)
    unname(tools::md5sum(path))
}

beta_shape2_from_mean <- function(mean_abundance, shape1) {
    mean_abundance <- as.numeric(mean_abundance)
    shape1 <- as.numeric(shape1)
    if (length(shape1) != 1L || !is.finite(shape1) || shape1 <= 0 ||
        any(!is.finite(mean_abundance)) ||
        any(mean_abundance <= 0 | mean_abundance >= 1)) {
        stop("Invalid beta-distribution parameters.", call. = FALSE)
    }
    shape1 * (1 - mean_abundance) / mean_abundance
}

beta_detection_probability <- function(N, mean_abundance, shape1) {
    N <- as.numeric(N)
    shape2 <- beta_shape2_from_mean(mean_abundance, shape1)
    log_p_zero <- lbeta(shape1, shape2 + N) - lbeta(shape1, shape2)
    p_detect <- -expm1(log_p_zero)
    pmin(pmax(p_detect, 0), 1)
}

expected_observed_prevalence <- function(N, rho, mean_abundance, shape1) {
    (1 - rho) * mean(beta_detection_probability(
        N = N,
        mean_abundance = mean_abundance,
        shape1 = shape1
    ))
}

solve_mean_for_prevalence <- function(N, rho, target_prevalence, shape1) {
    objective <- function(mean_abundance) {
        expected_observed_prevalence(
            N = N,
            rho = rho,
            mean_abundance = mean_abundance,
            shape1 = shape1
        ) - target_prevalence
    }
    lower <- 1e-8
    upper <- 0.02
    f_lower <- objective(lower)
    f_upper <- objective(upper)
    if (!is.finite(f_lower) || !is.finite(f_upper) ||
        f_lower > 0 || f_upper < 0) {
        stop(
            sprintf(
                paste0("Could not match observed prevalence: target=%.6f, ",
                       "rho=%.6f, lower residual=%.6g, upper residual=%.6g."),
                target_prevalence, rho, f_lower, f_upper
            ),
            call. = FALSE
        )
    }
    stats::uniroot(objective, interval = c(lower, upper),
                   tol = 1e-12)$root
}

make_target_specs <- function(N_reference, N_comparison, config) {
    rho0 <- config$base_structural_absence
    mu_structural0 <- config$structural_base_relative_abundance
    mu_detectability0 <- config$detectability_base_relative_abundance
    shape1 <- config$beta_shape1
    rows <- list()
    row_id <- 0L

    structural_baseline_prevalence <- expected_observed_prevalence(
        N_reference, rho0, mu_structural0, shape1
    )
    detectability_baseline_prevalence <- expected_observed_prevalence(
        N_reference, rho0, mu_detectability0, shape1
    )

    for (k in seq_along(config$structural_log_odds_effects)) {
        effect <- config$structural_log_odds_effects[k]
        rho1 <- stats::plogis(stats::qlogis(rho0) + effect)
        mu1 <- solve_mean_for_prevalence(
            N = N_comparison,
            rho = rho1,
            target_prevalence = structural_baseline_prevalence,
            shape1 = shape1
        )
        prev1 <- expected_observed_prevalence(
            N_comparison, rho1, mu1, shape1
        )
        row_id <- row_id + 1L
        rows[[row_id]] <- data.frame(
            target = sprintf("SA_masked_E%02d", k - 1L),
            scenario = "structural_masked",
            scenario_label = paste0(
                "Structural-absence difference\nwith matched observed prevalence"
            ),
            effect_index = k - 1L,
            effect_parameter = effect,
            effect_parameter_name = "structural log-odds shift",
            rho_reference = rho0,
            rho_comparison = rho1,
            mean_abundance_reference = mu_structural0,
            mean_abundance_comparison = mu1,
            expected_prevalence_reference = structural_baseline_prevalence,
            expected_prevalence_comparison = prev1,
            stringsAsFactors = FALSE
        )
    }

    for (k in seq_along(config$detectability_log_abundance_effects)) {
        effect <- config$detectability_log_abundance_effects[k]
        mu1 <- mu_detectability0 * exp(-effect)
        prev1 <- expected_observed_prevalence(
            N_comparison, rho0, mu1, shape1
        )
        row_id <- row_id + 1L
        rows[[row_id]] <- data.frame(
            target = sprintf("Detection_E%02d", k - 1L),
            scenario = "detectability_only",
            scenario_label = paste0(
                "Observed-prevalence difference\nwith no structural-absence difference"
            ),
            effect_index = k - 1L,
            effect_parameter = effect,
            effect_parameter_name = "log conditional-abundance decrease",
            rho_reference = rho0,
            rho_comparison = rho0,
            mean_abundance_reference = mu_detectability0,
            mean_abundance_comparison = mu1,
            expected_prevalence_reference = detectability_baseline_prevalence,
            expected_prevalence_comparison = prev1,
            stringsAsFactors = FALSE
        )
    }

    if (isTRUE(config$include_concordant_structural_scenario)) {
        for (k in seq_along(config$structural_log_odds_effects)) {
            effect <- config$structural_log_odds_effects[k]
            rho1 <- stats::plogis(stats::qlogis(rho0) + effect)
            prev1 <- expected_observed_prevalence(
                N_comparison, rho1, mu_structural0, shape1
            )
            row_id <- row_id + 1L
            rows[[row_id]] <- data.frame(
                target = sprintf("SA_concordant_E%02d", k - 1L),
                scenario = "structural_concordant",
                scenario_label = paste0(
                    "Structural-absence difference\nwith an observed-prevalence difference"
                ),
                effect_index = k - 1L,
                effect_parameter = effect,
                effect_parameter_name = "structural log-odds shift",
                rho_reference = rho0,
                rho_comparison = rho1,
                mean_abundance_reference = mu_structural0,
                mean_abundance_comparison = mu_structural0,
                expected_prevalence_reference = structural_baseline_prevalence,
                expected_prevalence_comparison = prev1,
                stringsAsFactors = FALSE
            )
        }
    }

    specs <- do.call(rbind, rows)
    rownames(specs) <- specs$target
    specs$structural_absence_difference <-
        specs$rho_comparison - specs$rho_reference
    specs$observed_prevalence_difference <-
        specs$expected_prevalence_comparison -
        specs$expected_prevalence_reference
    specs$beta_shape1 <- shape1
    specs$beta_shape2_reference <- beta_shape2_from_mean(
        specs$mean_abundance_reference, shape1
    )
    specs$beta_shape2_comparison <- beta_shape2_from_mean(
        specs$mean_abundance_comparison, shape1
    )
    specs$conditional_logit_sd_reference <- sqrt(
        trigamma(shape1) + trigamma(specs$beta_shape2_reference)
    )
    specs$conditional_logit_sd_comparison <- sqrt(
        trigamma(shape1) + trigamma(specs$beta_shape2_comparison)
    )
    specs
}

background_rank_weights <- function(n_taxa) {
    ranks <- seq_len(n_taxa)
    weights <- ranks^(-1.15)
    weights / sum(weights)
}

simulate_dataset <- function(rep_id, config) {
    set.seed(config$base_seed + as.integer(rep_id) * 100003L)
    n0 <- config$n_per_group
    n1 <- config$n_per_group
    n <- n0 + n1
    g <- c(rep(0L, n0), rep(1L, n1))

    depth_reference <- round(stats::rlnorm(
        n0,
        meanlog = log(config$depth_median),
        sdlog = config$depth_sdlog
    ))
    depth_reference <- pmin(
        pmax(depth_reference, config$depth_min), config$depth_max
    )
    depth_comparison <- sample(depth_reference, size = n1, replace = FALSE)
    depth <- as.integer(c(depth_reference, depth_comparison))

    sample_names <- sprintf("Sample_%03d", seq_len(n))
    metadata <- data.frame(
        group = factor(ifelse(g == 0L, "control", "case"),
                       levels = c("control", "case")),
        reads = depth,
        log_depth = as.numeric(scale(log(depth))),
        row.names = sample_names,
        stringsAsFactors = FALSE
    )

    specs <- make_target_specs(depth_reference, depth_comparison, config)
    target_names <- specs$target
    n_targets <- nrow(specs)
    target_probability <- matrix(
        0,
        nrow = n,
        ncol = n_targets,
        dimnames = list(sample_names, target_names)
    )
    latent_absent <- matrix(
        FALSE,
        nrow = n,
        ncol = n_targets,
        dimnames = list(sample_names, target_names)
    )

    for (j in seq_len(n_targets)) {
        rho <- ifelse(g == 0L, specs$rho_reference[j],
                      specs$rho_comparison[j])
        mean_abundance <- ifelse(
            g == 0L,
            specs$mean_abundance_reference[j],
            specs$mean_abundance_comparison[j]
        )
        absent <- stats::rbinom(n, size = 1L, prob = rho) == 1L
        present_probability <- stats::rbeta(
            n,
            shape1 = config$beta_shape1,
            shape2 = beta_shape2_from_mean(
                mean_abundance, config$beta_shape1
            )
        )
        present_probability[absent] <- 0
        target_probability[, j] <- present_probability
        latent_absent[, j] <- absent
    }

    target_total <- rowSums(target_probability)
    guarded <- target_total > config$target_probability_guard
    if (any(guarded)) {
        target_probability[guarded, ] <-
            target_probability[guarded, , drop = FALSE] *
            (config$target_probability_guard / target_total[guarded])
        target_total <- rowSums(target_probability)
    }

    n_background <- config$n_background_taxa
    background_names <- sprintf("Background_%02d", seq_len(n_background))
    background_base <- background_rank_weights(n_background)
    background_alpha <- pmax(
        config$background_dirichlet_concentration * background_base,
        0.02
    )

    feature_names <- c(target_names, background_names)
    full_counts <- matrix(
        0L,
        nrow = n,
        ncol = length(feature_names),
        dimnames = list(sample_names, feature_names)
    )

    for (i in seq_len(n)) {
        background_draw <- stats::rgamma(
            n_background,
            shape = background_alpha,
            rate = 1
        )
        background_draw <- background_draw / sum(background_draw)
        probabilities <- c(
            target_probability[i, ],
            (1 - target_total[i]) * background_draw
        )
        probabilities <- pmax(probabilities, 0)
        probabilities <- probabilities / sum(probabilities)
        full_counts[i, ] <- as.integer(stats::rmultinom(
            1L, size = depth[i], prob = probabilities
        )[, 1L])
    }

    target_counts <- full_counts[, target_names, drop = FALSE]
    truth <- specs
    truth$replicate <- rep_id
    truth$actual_structural_absence_reference <- vapply(
        seq_len(n_targets),
        function(j) mean(latent_absent[g == 0L, j]),
        numeric(1)
    )
    truth$actual_structural_absence_comparison <- vapply(
        seq_len(n_targets),
        function(j) mean(latent_absent[g == 1L, j]),
        numeric(1)
    )
    truth$actual_prevalence_reference <- vapply(
        seq_len(n_targets),
        function(j) mean(target_counts[g == 0L, j] > 0),
        numeric(1)
    )
    truth$actual_prevalence_comparison <- vapply(
        seq_len(n_targets),
        function(j) mean(target_counts[g == 1L, j] > 0),
        numeric(1)
    )
    truth$probability_guarded_samples <- sum(guarded)

    list(
        full_counts = full_counts,
        target_counts = target_counts,
        metadata = metadata,
        truth = truth,
        target_names = target_names
    )
}

empty_method_result <- function(target_names, method, status,
                                warning = NA_character_) {
    data.frame(
        target = target_names,
        method = method,
        p_value = NA_real_,
        statistic = NA_real_,
        coefficient = NA_real_,
        available = FALSE,
        status = status,
        warning = warning,
        abundance_induced_flag = NA,
        stringsAsFactors = FALSE
    )
}

run_dasra_structural <- function(sim, dasra_function) {
    target_names <- sim$target_names
    warning_text <- character()
    fit <- tryCatch(
        withCallingHandlers(
            dasra_function(
                counts = t(sim$target_counts),
                metadata = sim$metadata,
                formula = ~ group,
                group = "group",
                library_size = "reads",
                taxa_are_rows = TRUE,
                reference = "control",
                component = "structural_absence",
                full_output = FALSE
            ),
            warning = function(w) {
                warning_text <<- c(warning_text, conditionMessage(w))
                invokeRestart("muffleWarning")
            }
        ),
        error = function(e) e
    )
    if (inherits(fit, "error")) {
        return(empty_method_result(
            target_names,
            method = "DASRA structural absence",
            status = paste0("error: ", conditionMessage(fit))
        ))
    }

    result <- fit$results
    diagnostics <- fit$diagnostics
    result_index <- match(target_names, result$taxon)
    diagnostic_index <- match(target_names, diagnostics$taxon)
    formed <- as.logical(
        diagnostics$formed_structural_absence[diagnostic_index]
    )
    p_value <- as.numeric(result$p_structural_absence[result_index])
    statistic <- if ("z_structural_absence" %in% names(result)) {
        as.numeric(result$z_structural_absence[result_index])
    } else {
        rep(NA_real_, length(target_names))
    }
    reason <- as.character(
        diagnostics$reason_structural_absence[diagnostic_index]
    )
    available <- formed & is.finite(p_value) & p_value >= 0 & p_value <= 1
    p_value[!available] <- NA_real_
    statistic[!available] <- NA_real_
    reason[available] <- "ok"

    data.frame(
        target = target_names,
        method = "DASRA structural absence",
        p_value = p_value,
        statistic = statistic,
        coefficient = NA_real_,
        available = available,
        status = reason,
        warning = collapse_conditions(warning_text),
        abundance_induced_flag = NA,
        stringsAsFactors = FALSE
    )
}

run_zinq_prevalence <- function(sim, config, rep_id) {
    target_names <- sim$target_names
    rows <- vector("list", length(target_names))
    for (j in seq_along(target_names)) {
        target <- target_names[j]
        dat <- data.frame(
            Y = as.numeric(sim$target_counts[, target]),
            group = as.numeric(sim$metadata$group == "case"),
            log_depth = sim$metadata$log_depth
        )
        warning_text <- character()
        official <- tryCatch(
            withCallingHandlers(
                ZINQ::ZINQ_tests(
                    formula.logistic = Y ~ group + log_depth,
                    formula.quantile = Y ~ group + log_depth,
                    C = "group",
                    y_CorD = "D",
                    data = dat,
                    taus = config$zinq_quantile_tau,
                    seed = config$base_seed + rep_id * 1009L + j
                ),
                warning = function(w) {
                    warning_text <<- c(warning_text, conditionMessage(w))
                    invokeRestart("muffleWarning")
                }
            ),
            error = function(e) e
        )

        p_value <- NA_real_
        status <- "official_function_failed"
        if (!inherits(official, "error")) {
            p_candidate <- as.numeric(official$pvalue.logistic)[1L]
            if (is.finite(p_candidate) && p_candidate >= 0 && p_candidate <= 1) {
                p_value <- p_candidate
                status <- "ok"
            }
        }

        if (!is.finite(p_value)) {
            dat$detected <- as.integer(dat$Y > 0)
            fallback <- tryCatch(
                withCallingHandlers(
                    logistf::logistf(
                        detected ~ group + log_depth,
                        data = dat
                    ),
                    warning = function(w) {
                        warning_text <<- c(warning_text, conditionMessage(w))
                        invokeRestart("muffleWarning")
                    }
                ),
                error = function(e) e
            )
            if (!inherits(fallback, "error")) {
                p_names <- names(fallback$prob)
                p_position <- match("group", p_names)
                if (!is.finite(p_position)) p_position <- 2L
                p_candidate <- as.numeric(fallback$prob[p_position])
                if (is.finite(p_candidate) && p_candidate >= 0 &&
                    p_candidate <= 1) {
                    p_value <- p_candidate
                    status <- "official_firth_prevalence_fallback"
                }
            } else {
                status <- paste0("error: ", conditionMessage(fallback))
            }
        }

        rows[[j]] <- data.frame(
            target = target,
            method = "ZINQ Firth prevalence",
            p_value = p_value,
            statistic = NA_real_,
            coefficient = NA_real_,
            available = is.finite(p_value),
            status = status,
            warning = collapse_conditions(warning_text),
            abundance_induced_flag = NA,
            stringsAsFactors = FALSE
        )
    }
    do.call(rbind, rows)
}

extract_maaslin3_prevalence_results <- function(fit, target_names) {
    prevalence <- fit$fit_data_prevalence
    results <- if (is.data.frame(prevalence)) {
        prevalence
    } else {
        prevalence$results
    }
    if (is.null(results) || !is.data.frame(results)) {
        return(empty_method_result(
            target_names,
            method = "MaAsLin 3 prevalence",
            status = "prevalence_results_unavailable"
        ))
    }

    rows <- vector("list", length(target_names))
    for (j in seq_along(target_names)) {
        target <- target_names[j]
        candidates <- results[results$feature == target, , drop = FALSE]
        if ("metadata" %in% names(candidates)) {
            candidates <- candidates[candidates$metadata == "group", , drop = FALSE]
        }
        if (nrow(candidates) > 1L && "value" %in% names(candidates)) {
            preferred <- candidates$value == "case"
            if (any(preferred, na.rm = TRUE)) {
                candidates <- candidates[which(preferred)[1L], , drop = FALSE]
            }
        }
        if (nrow(candidates) > 1L && "name" %in% names(candidates)) {
            preferred <- candidates$name %in% c("groupcase", "group case")
            if (any(preferred, na.rm = TRUE)) {
                candidates <- candidates[which(preferred)[1L], , drop = FALSE]
            }
        }
        if (!nrow(candidates)) {
            rows[[j]] <- empty_method_result(
                target,
                method = "MaAsLin 3 prevalence",
                status = "target_prevalence_row_unavailable"
            )
            next
        }
        candidate <- candidates[1L, , drop = FALSE]
        p_value <- as.numeric(candidate$pval_individual)[1L]
        coefficient <- if ("coef" %in% names(candidate)) {
            as.numeric(candidate$coef)[1L]
        } else {
            NA_real_
        }
        error_text <- if ("error" %in% names(candidate)) {
            as.character(candidate$error)[1L]
        } else {
            NA_character_
        }
        if (identical(error_text, "NA") || is.na(error_text) ||
            !nzchar(trimws(error_text))) {
            error_text <- NA_character_
        }
        available <- is.finite(p_value) && p_value >= 0 && p_value <= 1
        rows[[j]] <- data.frame(
            target = target,
            method = "MaAsLin 3 prevalence",
            p_value = if (available) p_value else NA_real_,
            statistic = NA_real_,
            coefficient = if (available) coefficient else NA_real_,
            available = available,
            status = if (available) {
                "ok"
            } else if (is.na(error_text) || !nzchar(trimws(error_text))) {
                "nonfinite_p_value"
            } else {
                error_text
            },
            warning = error_text,
            abundance_induced_flag = if (is.na(error_text)) {
                FALSE
            } else {
                grepl("abundance|induced", error_text, ignore.case = TRUE)
            },
            stringsAsFactors = FALSE
        )
    }
    do.call(rbind, rows)
}

run_maaslin3_prevalence <- function(sim, config, rep_id) {
    target_names <- sim$target_names
    output_dir <- tempfile(sprintf("maaslin3_rep_%04d_", rep_id))
    on.exit({
        try(maaslin3::maaslin_log_reset(), silent = TRUE)
        unlink(output_dir, recursive = TRUE, force = TRUE)
    }, add = TRUE)

    try(maaslin3::maaslin_log_reset(), silent = TRUE)
    warning_text <- character()
    fit <- tryCatch(
        {
            invisible(capture.output(
                fit_value <- withCallingHandlers(
                    suppressMessages(maaslin3::maaslin3(
                        input_data = as.data.frame(sim$full_counts),
                        input_metadata = sim$metadata,
                        output = output_dir,
                        formula = "~ group + log_depth",
                        min_abundance = 0,
                        min_prevalence = 0,
                        max_prevalence = 1.01,
                        zero_threshold = 0,
                        min_variance = 0,
                        normalization = "TSS",
                        transform = "LOG",
                        correction = "BH",
                        standardize = TRUE,
                        median_comparison_abundance = TRUE,
                        median_comparison_prevalence = FALSE,
                        warn_prevalence = isTRUE(
                            config$maaslin3_keep_abundance_warning
                        ),
                        augment = TRUE,
                        evaluate_only = NULL,
                        plot_summary_plot = FALSE,
                        plot_associations = FALSE,
                        max_pngs = 1,
                        cores = 1,
                        save_models = FALSE,
                        save_plots_rds = FALSE,
                        verbosity = "ERROR"
                    )),
                    warning = function(w) {
                        warning_text <<- c(warning_text, conditionMessage(w))
                        invokeRestart("muffleWarning")
                    }
                )
            ))
            fit_value
        },
        error = function(e) e
    )

    if (inherits(fit, "error")) {
        return(empty_method_result(
            target_names,
            method = "MaAsLin 3 prevalence",
            status = paste0("error: ", conditionMessage(fit)),
            warning = collapse_conditions(warning_text)
        ))
    }

    out <- extract_maaslin3_prevalence_results(fit, target_names)
    global_warning <- collapse_conditions(warning_text)
    if (!is.na(global_warning)) {
        out$warning <- ifelse(
            is.na(out$warning),
            global_warning,
            paste(out$warning, global_warning, sep = " | ")
        )
    }
    out
}

analyze_one_replicate <- function(rep_id, config, dasra_function,
                                  checkpoint_dir, run_signature) {
    checkpoint_file <- file.path(
        checkpoint_dir, sprintf("replicate_%04d.rds", rep_id)
    )
    if (isTRUE(config$resume) && file.exists(checkpoint_file)) {
        existing <- tryCatch(readRDS(checkpoint_file), error = function(e) NULL)
        if (!is.null(existing) && isTRUE(existing$success) &&
            identical(existing$run_signature, run_signature)) {
            return(existing)
        }
    }

    result <- tryCatch({
        sim <- simulate_dataset(rep_id, config)
        method_results <- dplyr::bind_rows(
            run_dasra_structural(sim, dasra_function),
            run_zinq_prevalence(sim, config, rep_id),
            run_maaslin3_prevalence(sim, config, rep_id)
        )
        raw <- dplyr::left_join(
            method_results,
            sim$truth,
            by = "target"
        )
        raw$replicate <- rep_id
        raw$reject <- ifelse(
            raw$available,
            raw$p_value < config$alpha,
            NA
        )
        list(
            success = TRUE,
            replicate = rep_id,
            run_signature = run_signature,
            raw = raw,
            truth = sim$truth,
            error = NA_character_
        )
    }, error = function(e) {
        list(
            success = FALSE,
            replicate = rep_id,
            run_signature = run_signature,
            raw = NULL,
            truth = NULL,
            error = conditionMessage(e)
        )
    })

    temporary_file <- paste0(
        checkpoint_file, ".tmp_", Sys.getpid(), "_", sample.int(1e8, 1L)
    )
    saveRDS(result, temporary_file)
    if (!file.rename(temporary_file, checkpoint_file)) {
        unlink(temporary_file)
        stop("Could not write replicate checkpoint: ", checkpoint_file,
             call. = FALSE)
    }
    result
}

wilson_interval <- function(successes, total, confidence = 0.95) {
    if (!is.finite(total) || total <= 0) return(c(NA_real_, NA_real_))
    z <- stats::qnorm(1 - (1 - confidence) / 2)
    p <- successes / total
    denominator <- 1 + z^2 / total
    center <- (p + z^2 / (2 * total)) / denominator
    half_width <- z * sqrt(
        p * (1 - p) / total + z^2 / (4 * total^2)
    ) / denominator
    c(max(0, center - half_width), min(1, center + half_width))
}

summarize_results <- function(raw_results, truth_results, config) {
    method_order <- c(
        "DASRA structural absence",
        "ZINQ Firth prevalence",
        "MaAsLin 3 prevalence"
    )
    raw_results$method <- factor(raw_results$method, levels = method_order)

    summary <- raw_results |>
        dplyr::group_by(
            scenario, scenario_label, effect_index, effect_parameter,
            effect_parameter_name, target, method
        ) |>
        dplyr::summarise(
            n_total = dplyr::n(),
            n_available = sum(available, na.rm = TRUE),
            availability_rate = mean(available, na.rm = TRUE),
            n_reject = sum(reject %in% TRUE, na.rm = TRUE),
            conditional_rejection_rate = ifelse(
                n_available > 0,
                n_reject / n_available,
                NA_real_
            ),
            rejection_rate = n_reject / n_total,
            overall_rejection_fraction = rejection_rate,
            maaslin3_abundance_induced_flag_rate = ifelse(
                any(!is.na(abundance_induced_flag)),
                mean(abundance_induced_flag, na.rm = TRUE),
                NA_real_
            ),
            .groups = "drop"
        )

    intervals <- t(vapply(
        seq_len(nrow(summary)),
        function(i) wilson_interval(
            summary$n_reject[i], summary$n_total[i]
        ),
        numeric(2)
    ))
    summary$ci_lower <- intervals[, 1L]
    summary$ci_upper <- intervals[, 2L]

    conditional_intervals <- t(vapply(
        seq_len(nrow(summary)),
        function(i) wilson_interval(
            summary$n_reject[i], summary$n_available[i]
        ),
        numeric(2)
    ))
    summary$conditional_ci_lower <- conditional_intervals[, 1L]
    summary$conditional_ci_upper <- conditional_intervals[, 2L]

    truth_summary <- truth_results |>
        dplyr::group_by(
            scenario, scenario_label, effect_index, effect_parameter,
            effect_parameter_name, target
        ) |>
        dplyr::summarise(
            rho_reference = mean(rho_reference),
            rho_comparison = mean(rho_comparison),
            mean_abundance_reference = mean(mean_abundance_reference),
            mean_abundance_comparison = mean(mean_abundance_comparison),
            expected_prevalence_reference = mean(expected_prevalence_reference),
            expected_prevalence_comparison = mean(expected_prevalence_comparison),
            beta_shape1 = mean(beta_shape1),
            beta_shape2_reference = mean(beta_shape2_reference),
            beta_shape2_comparison = mean(beta_shape2_comparison),
            conditional_logit_sd_reference = mean(
                conditional_logit_sd_reference
            ),
            conditional_logit_sd_comparison = mean(
                conditional_logit_sd_comparison
            ),
            expected_structural_absence_difference = mean(
                structural_absence_difference
            ),
            expected_observed_prevalence_difference = mean(
                observed_prevalence_difference
            ),
            actual_structural_absence_reference = mean(
                actual_structural_absence_reference
            ),
            actual_structural_absence_comparison = mean(
                actual_structural_absence_comparison
            ),
            actual_prevalence_reference = mean(actual_prevalence_reference),
            actual_prevalence_comparison = mean(actual_prevalence_comparison),
            mean_probability_guarded_samples = mean(
                probability_guarded_samples
            ),
            .groups = "drop"
        )
    truth_summary$actual_structural_absence_difference <-
        truth_summary$actual_structural_absence_comparison -
        truth_summary$actual_structural_absence_reference
    truth_summary$actual_observed_prevalence_difference <-
        truth_summary$actual_prevalence_comparison -
        truth_summary$actual_prevalence_reference

    summary <- dplyr::left_join(
        summary,
        truth_summary,
        by = c(
            "scenario", "scenario_label", "effect_index", "effect_parameter",
            "effect_parameter_name", "target"
        )
    )
    list(raw = raw_results, summary = summary, truth = truth_summary)
}

publication_theme <- function() {
    ggplot2::theme_classic(base_size = 12) +
        ggplot2::theme(
            legend.position = "top",
            legend.title = ggplot2::element_blank(),
            axis.title = ggplot2::element_text(size = 12),
            axis.text = ggplot2::element_text(size = 10),
            panel.grid = ggplot2::element_blank(),
            plot.margin = ggplot2::margin(6, 8, 6, 6)
        )
}

method_scales <- function() {
    list(
        colors = c(
            "DASRA structural absence" = "#0072B2",
            "ZINQ Firth prevalence" = "#D55E00",
            "MaAsLin 3 prevalence" = "#009E73"
        ),
        shapes = c(
            "DASRA structural absence" = 16,
            "ZINQ Firth prevalence" = 17,
            "MaAsLin 3 prevalence" = 15
        ),
        linetypes = c(
            "DASRA structural absence" = "solid",
            "ZINQ Firth prevalence" = "dashed",
            "MaAsLin 3 prevalence" = "dotdash"
        )
    )
}

save_publication_plot <- function(plot, stem, output_dir,
                                  width = 6.6, height = 4.6) {
    pdf_file <- file.path(output_dir, paste0(stem, ".pdf"))
    png_file <- file.path(output_dir, paste0(stem, ".png"))
    pdf_device <- if (capabilities("cairo")) grDevices::cairo_pdf else "pdf"
    ggplot2::ggsave(
        pdf_file, plot = plot, width = width, height = height,
        units = "in", device = pdf_device
    )
    ggplot2::ggsave(
        png_file, plot = plot, width = width, height = height,
        units = "in", dpi = 600, bg = "white"
    )
}

plot_rejection_scenario <- function(summary, scenario, x_variable, x_label,
                                    output_stem, output_dir, alpha) {
    plot_data <- summary[summary$scenario == scenario, , drop = FALSE]
    plot_data$x_value <- abs(plot_data[[x_variable]])
    scales <- method_scales()
    p <- ggplot2::ggplot(
        plot_data,
        ggplot2::aes(
            x = x_value,
            y = rejection_rate,
            color = method,
            shape = method,
            linetype = method,
            group = method
        )
    ) +
        ggplot2::geom_hline(
            yintercept = alpha,
            linewidth = 0.45,
            linetype = "dotted",
            color = "grey35"
        ) +
        ggplot2::geom_errorbar(
            ggplot2::aes(ymin = ci_lower, ymax = ci_upper),
            width = 0,
            linewidth = 0.45
        ) +
        ggplot2::geom_line(linewidth = 0.75) +
        ggplot2::geom_point(size = 2.4, stroke = 0.7) +
        ggplot2::scale_color_manual(values = scales$colors, drop = FALSE) +
        ggplot2::scale_shape_manual(values = scales$shapes, drop = FALSE) +
        ggplot2::scale_linetype_manual(values = scales$linetypes, drop = FALSE) +
        ggplot2::scale_y_continuous(
            limits = c(0, 1),
            breaks = seq(0, 1, by = 0.2),
            expand = ggplot2::expansion(mult = c(0, 0.02))
        ) +
        ggplot2::scale_x_continuous(
            breaks = sort(unique(round(plot_data$x_value, 3))),
            labels = function(x) format(round(x, 3), trim = TRUE),
            expand = ggplot2::expansion(mult = c(0.03, 0.03))
        ) +
        ggplot2::labs(
            x = x_label,
            y = "Empirical rejection rate"
        ) +
        publication_theme()
    save_publication_plot(p, output_stem, output_dir)
    p
}

plot_combined_rejection <- function(summary, output_dir, alpha) {
    scales <- method_scales()
    p <- ggplot2::ggplot(
        summary,
        ggplot2::aes(
            x = effect_index,
            y = rejection_rate,
            color = method,
            shape = method,
            linetype = method,
            group = method
        )
    ) +
        ggplot2::geom_hline(
            yintercept = alpha,
            linewidth = 0.45,
            linetype = "dotted",
            color = "grey35"
        ) +
        ggplot2::geom_errorbar(
            ggplot2::aes(ymin = ci_lower, ymax = ci_upper),
            width = 0,
            linewidth = 0.4
        ) +
        ggplot2::geom_line(linewidth = 0.7) +
        ggplot2::geom_point(size = 2.2, stroke = 0.7) +
        ggplot2::facet_wrap(~ scenario_label, nrow = 1) +
        ggplot2::scale_color_manual(values = scales$colors, drop = FALSE) +
        ggplot2::scale_shape_manual(values = scales$shapes, drop = FALSE) +
        ggplot2::scale_linetype_manual(values = scales$linetypes, drop = FALSE) +
        ggplot2::scale_y_continuous(
            limits = c(0, 1),
            breaks = seq(0, 1, by = 0.2),
            expand = ggplot2::expansion(mult = c(0, 0.02))
        ) +
        ggplot2::scale_x_continuous(
            breaks = sort(unique(summary$effect_index))
        ) +
        ggplot2::labs(
            x = "Effect level",
            y = "Empirical rejection rate"
        ) +
        publication_theme() +
        ggplot2::theme(
            strip.background = ggplot2::element_blank(),
            strip.text = ggplot2::element_text(size = 10)
        )
    save_publication_plot(
        p,
        "fig_rejection_rates_combined",
        output_dir,
        width = ifelse(length(unique(summary$scenario)) > 2, 10.5, 8.0),
        height = 4.2
    )
    p
}

plot_availability <- function(summary, output_dir) {
    scales <- method_scales()
    p <- ggplot2::ggplot(
        summary,
        ggplot2::aes(
            x = effect_index,
            y = availability_rate,
            color = method,
            shape = method,
            linetype = method,
            group = method
        )
    ) +
        ggplot2::geom_line(linewidth = 0.7) +
        ggplot2::geom_point(size = 2.2) +
        ggplot2::facet_wrap(~ scenario_label, nrow = 1) +
        ggplot2::scale_color_manual(values = scales$colors, drop = FALSE) +
        ggplot2::scale_shape_manual(values = scales$shapes, drop = FALSE) +
        ggplot2::scale_linetype_manual(values = scales$linetypes, drop = FALSE) +
        ggplot2::scale_y_continuous(
            limits = c(0, 1), breaks = seq(0, 1, 0.2),
            expand = ggplot2::expansion(mult = c(0, 0.02))
        ) +
        ggplot2::scale_x_continuous(breaks = sort(unique(summary$effect_index))) +
        ggplot2::labs(x = "Effect level", y = "Proportion of tests available") +
        publication_theme() +
        ggplot2::theme(
            strip.background = ggplot2::element_blank(),
            strip.text = ggplot2::element_text(size = 10)
        )
    save_publication_plot(
        p, "fig_method_availability", output_dir,
        width = ifelse(length(unique(summary$scenario)) > 2, 10.5, 8.0),
        height = 4.2
    )
    p
}

plot_design_verification <- function(truth_summary, output_dir) {
    structural <- data.frame(
        truth_summary[, c("scenario_label", "effect_index")],
        metric = "Structural-absence probability difference",
        value = abs(truth_summary$expected_structural_absence_difference)
    )
    prevalence <- data.frame(
        truth_summary[, c("scenario_label", "effect_index")],
        metric = "Expected observed-prevalence difference",
        value = abs(truth_summary$expected_observed_prevalence_difference)
    )
    plot_data <- rbind(structural, prevalence)
    p <- ggplot2::ggplot(
        plot_data,
        ggplot2::aes(x = effect_index, y = value, group = metric,
                     shape = metric, linetype = metric)
    ) +
        ggplot2::geom_line(linewidth = 0.7) +
        ggplot2::geom_point(size = 2.3) +
        ggplot2::facet_wrap(~ scenario_label, scales = "free_y", nrow = 1) +
        ggplot2::scale_shape_manual(values = c(16, 17)) +
        ggplot2::scale_linetype_manual(values = c("solid", "dashed")) +
        ggplot2::scale_x_continuous(breaks = sort(unique(plot_data$effect_index))) +
        ggplot2::labs(
            x = "Effect level",
            y = "Absolute probability difference",
            shape = NULL,
            linetype = NULL
        ) +
        publication_theme() +
        ggplot2::theme(
            strip.background = ggplot2::element_blank(),
            strip.text = ggplot2::element_text(size = 10)
        )
    save_publication_plot(
        p, "fig_simulation_design_verification", output_dir,
        width = ifelse(length(unique(plot_data$scenario_label)) > 2, 10.5, 8.0),
        height = 4.2
    )
    p
}

write_method_settings <- function(config, package_info, output_dir) {
    settings <- data.frame(
        method = c(
            "DASRA structural absence",
            "ZINQ Firth prevalence",
            "MaAsLin 3 prevalence"
        ),
        estimand = c(
            "Group effect on structural-absence probability",
            "Group effect on observed detection probability",
            "Group effect on observed presence/absence"
        ),
        implementation = c(
            paste0(
                package_info$dasra_namespace,
                "::dasra(component = 'structural_absence')"
            ),
            paste0(
                "ZINQ::ZINQ_tests logistic arm; exact logistf fallback ",
                "only when the unrelated quantile arm fails"
            ),
            paste0(
                "maaslin3::maaslin3 full recommended run; prevalence ",
                "pval_individual extracted"
            )
        ),
        adjustment = c(
            "Sequencing depth enters the finite-depth count model",
            "Standardized log sequencing depth in Firth logistic model",
            "Standardized log sequencing depth in MaAsLin 3 formula"
        ),
        key_options = c(
            "Raw counts; reference = control",
            "y_CorD = D; one quantile used only to execute official wrapper",
            paste0(
                "TSS, LOG, standardize = TRUE, augment = TRUE, ",
                "warn_prevalence = TRUE, median_comparison_prevalence = FALSE"
            )
        ),
        stringsAsFactors = FALSE
    )
    utils::write.csv(
        settings,
        file.path(output_dir, "method_settings.csv"),
        row.names = FALSE
    )
}

write_session_information <- function(config, package_info, output_dir) {
    package_names <- c(
        package_info$dasra_namespace, "ZINQ", "maaslin3", "logistf",
        "ggplot2", "dplyr"
    )
    versions <- vapply(package_names, function(pkg) {
        as.character(utils::packageVersion(pkg))
    }, character(1))
    lines <- c(
        "DASRA structural-absence versus observed-prevalence simulation",
        paste0("Run date: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
        "",
        "Configuration:",
        capture.output(str(config)),
        "",
        "Package versions:",
        paste0(names(versions), ": ", versions),
        "",
        "DASRA implementation fingerprint:",
        package_info$dasra_fingerprint,
        "",
        "Session information:",
        capture.output(sessionInfo())
    )
    writeLines(lines, file.path(output_dir, "session_information.txt"))
}

main <- function() {
    validate_config(CONFIG)
    if (.Platform$OS.type == "windows" && CONFIG$n_cores > 1L) {
        stop(
            "This script uses parallel::mclapply and is configured for macOS/Linux. ",
            "Set DASRA_SIM_CORES=1 on Windows.",
            call. = FALSE
        )
    }
    package_info <- check_packages()

    output_dir <- normalizePath(
        CONFIG$output_dir,
        winslash = "/",
        mustWork = FALSE
    )
    checkpoint_dir <- file.path(output_dir, "replicate_checkpoints")
    dir.create(checkpoint_dir, recursive = TRUE, showWarnings = FALSE)

    design_config <- CONFIG
    design_config$n_rep <- NULL
    design_config$n_cores <- NULL
    design_config$output_dir <- NULL
    design_config$resume <- NULL
    software_versions <- vapply(
        c(package_info$dasra_namespace, "ZINQ", "maaslin3", "logistf"),
        function(pkg) as.character(utils::packageVersion(pkg)),
        character(1)
    )
    design_record <- list(
        design = design_config,
        software_versions = software_versions,
        software_fingerprints = c(
            DASRA = package_info$dasra_fingerprint
        ),
        runtime = c(
            R = R.version.string,
            platform = R.version$platform
        )
    )
    run_signature <- object_fingerprint(design_record)
    config_file <- file.path(output_dir, "simulation_design_config.rds")
    if (file.exists(config_file)) {
        previous <- readRDS(config_file)
        if (!identical(previous, design_record)) {
            stop(
                "The output directory contains checkpoints from a different design or software version. ",
                "Choose a new DASRA_SIM_OUTDIR.",
                call. = FALSE
            )
        }
    } else {
        saveRDS(design_record, config_file)
    }

    write_method_settings(CONFIG, package_info, output_dir)
    write_session_information(CONFIG, package_info, output_dir)

    message(sprintf(
        "Running %d replicate(s) with %d parallel worker(s).",
        CONFIG$n_rep, CONFIG$n_cores
    ))
    replicate_ids <- seq_len(CONFIG$n_rep)
    worker <- function(rep_id) {
        analyze_one_replicate(
            rep_id = rep_id,
            config = CONFIG,
            dasra_function = package_info$dasra,
            checkpoint_dir = checkpoint_dir,
            run_signature = run_signature
        )
    }
    replicate_results <- if (CONFIG$n_cores == 1L) {
        lapply(replicate_ids, worker)
    } else {
        parallel::mclapply(
            replicate_ids,
            worker,
            mc.cores = CONFIG$n_cores,
            mc.preschedule = TRUE,
            mc.set.seed = FALSE
        )
    }

    success <- vapply(replicate_results, function(x) isTRUE(x$success),
                      logical(1))
    if (any(!success)) {
        errors <- data.frame(
            replicate = vapply(
                replicate_results[!success], `[[`, integer(1), "replicate"
            ),
            error = vapply(
                replicate_results[!success], `[[`, character(1), "error"
            ),
            stringsAsFactors = FALSE
        )
        utils::write.csv(
            errors,
            file.path(output_dir, "replicate_errors.csv"),
            row.names = FALSE
        )
        warning(sprintf(
            "%d replicate(s) failed. Details are in replicate_errors.csv.",
            sum(!success)
        ), call. = FALSE)
    }
    successful_results <- replicate_results[success]
    if (!length(successful_results)) {
        stop("No simulation replicate completed successfully.", call. = FALSE)
    }

    raw_results <- dplyr::bind_rows(lapply(successful_results, `[[`, "raw"))
    truth_results <- dplyr::bind_rows(lapply(successful_results, `[[`, "truth"))
    summaries <- summarize_results(raw_results, truth_results, CONFIG)

    utils::write.csv(
        summaries$raw,
        file.path(output_dir, "combined_raw_results.csv"),
        row.names = FALSE
    )
    utils::write.csv(
        summaries$summary,
        file.path(output_dir, "combined_rejection_summary.csv"),
        row.names = FALSE
    )
    utils::write.csv(
        summaries$truth,
        file.path(output_dir, "combined_truth_summary.csv"),
        row.names = FALSE
    )
    utils::write.csv(
        truth_results,
        file.path(output_dir, "combined_truth_by_replicate.csv"),
        row.names = FALSE
    )

    failure_summary <- summaries$raw |>
        dplyr::filter(!available) |>
        dplyr::count(method, scenario, status, name = "n") |>
        dplyr::arrange(method, scenario, dplyr::desc(n))
    utils::write.csv(
        failure_summary,
        file.path(output_dir, "method_failure_summary.csv"),
        row.names = FALSE
    )

    warning_summary <- summaries$raw |>
        dplyr::filter(!is.na(warning), nzchar(trimws(warning))) |>
        dplyr::count(method, scenario, warning, name = "n") |>
        dplyr::arrange(method, scenario, dplyr::desc(n))
    utils::write.csv(
        warning_summary,
        file.path(output_dir, "method_warning_summary.csv"),
        row.names = FALSE
    )

    plot_rejection_scenario(
        summaries$summary,
        scenario = "structural_masked",
        x_variable = "expected_structural_absence_difference",
        x_label = "Difference in structural-absence probability",
        output_stem = "fig_structural_absence_signal",
        output_dir = output_dir,
        alpha = CONFIG$alpha
    )
    plot_rejection_scenario(
        summaries$summary,
        scenario = "detectability_only",
        x_variable = "expected_observed_prevalence_difference",
        x_label = "Absolute expected observed-prevalence difference",
        output_stem = "fig_observed_prevalence_signal",
        output_dir = output_dir,
        alpha = CONFIG$alpha
    )
    if ("structural_concordant" %in% summaries$summary$scenario) {
        plot_rejection_scenario(
            summaries$summary,
            scenario = "structural_concordant",
            x_variable = "expected_structural_absence_difference",
            x_label = "Difference in structural-absence probability",
            output_stem = "fig_concordant_structural_signal",
            output_dir = output_dir,
            alpha = CONFIG$alpha
        )
    }
    plot_combined_rejection(
        summaries$summary, output_dir, alpha = CONFIG$alpha
    )
    plot_availability(summaries$summary, output_dir)
    plot_design_verification(summaries$truth, output_dir)

    message("Simulation complete.")
    message("Output directory: ", output_dir)
    print(summaries$summary[, c(
        "scenario", "effect_index", "method", "n_available",
        "availability_rate", "rejection_rate",
        "conditional_rejection_rate", "ci_lower", "ci_upper"
    )])
    invisible(summaries)
}

main()
