#!/usr/bin/env Rscript

# =============================================================================
# DASRA present-conditional abundance simulation
# =============================================================================
#
# This standalone script implements a prototype of the proposed DASRA
# abundance component and compares it with:
#
#   1. the quantile-regression abundance component of ZINQ v2; and
#   2. the abundance component of MaAsLin 3.
#
# The proposed method uses the same latent structural-absence/count model as
# the DASRA structural component. It does not replace zeros with pseudocounts.
# Zero-count samples contribute to the abundance estimating equation through
# their posterior probability of ecological presence and their posterior
# latent-abundance score.
#
# The raw taxon-specific effect is a covariate-standardized difference in
# present-conditional mean log relative abundance. A target-excluded robust
# cross-taxon reference correction is then used to remove a shared
# compositional background, and sample-aligned influence contributions are
# used to propagate both taxon-specific and background-estimation uncertainty.
#
# Simulation strategy
# -------------------
# Counts are generated by a zero-inflated, correlated lognormal absolute-
# abundance model followed by multinomial sequencing. This is a common
# microbiome simulation strategy and deliberately differs from the
# taxon-specific logistic-normal working marginal used by the proposed method.
#
# Scenarios include:
#   * a global null;
#   * a sequencing-depth-imbalanced null;
#   * balanced present-conditional abundance signals;
#   * rare but ecologically widespread taxa with frequent finite-depth
#     nondetection;
#   * sparse and dense unidirectional abundance perturbations that stress
#     compositional correction;
#   * structural-absence differences with no direct abundance effects; and
#   * mixed structural-absence and abundance signals.
#
# Primary truth
# -------------
# A taxon is an abundance signal when its latent absolute abundance receives a
# direct group effect. This is the taxon-specific truth relevant to the
# compositionally centered DASRA and MaAsLin 3 median-comparison procedures.
# ZINQ's detected-sample quantile component targets a different, uncentered
# relative-abundance null; the script therefore also writes oracle latent-
# relative and detected-sample effect summaries so that estimand differences
# remain visible.
#
# Direct run
# ----------
#   Rscript dasra_present_conditional_abundance_simulation.R
#
# Recommended pilot
# -----------------
#   DASRA_ABUND_REPS=5 DASRA_ABUND_CORES=2 \
#     Rscript dasra_present_conditional_abundance_simulation.R
#
# Main run
# --------
#   DASRA_ABUND_REPS=100 DASRA_ABUND_CORES=8 \
#     Rscript dasra_present_conditional_abundance_simulation.R
#
# Optional environment variables
# ------------------------------
#   DASRA_ABUND_REPS=30
#   DASRA_ABUND_N_PER_GROUP=100
#   DASRA_ABUND_TAXA=30
#   DASRA_ABUND_CORES=8
#   DASRA_ABUND_OUTDIR=/path/to/output
#   DASRA_ABUND_RESUME=true
#   DASRA_ABUND_HEAVY_TAIL=false
#   DASRA_ABUND_Q=41
#
# Required packages
# -----------------
#   ZINQ, maaslin3, nleqslv, statmod, ggplot2, dplyr, tidyr
#
# Installation examples
# ---------------------
#   remotes::install_github("wdl2459/ZINQ-v2")
#   BiocManager::install("maaslin3")
#   install.packages(c("nleqslv", "statmod", "ggplot2", "dplyr", "tidyr"))
#
# =============================================================================

options(stringsAsFactors = FALSE, warn = 1)

Sys.setenv(
    OMP_NUM_THREADS = "1",
    OPENBLAS_NUM_THREADS = "1",
    MKL_NUM_THREADS = "1",
    VECLIB_MAXIMUM_THREADS = "1",
    NUMEXPR_NUM_THREADS = "1"
)

`%||%` <- function(x, y) {
    if (is.null(x)) y else x
}

env_flag <- function(name, default = FALSE) {
    value <- tolower(trimws(Sys.getenv(
        name, if (isTRUE(default)) "true" else "false"
    )))
    if (value %in% c("1", "true", "t", "yes", "y")) return(TRUE)
    if (value %in% c("0", "false", "f", "no", "n")) return(FALSE)
    stop(name, " must be true or false.", call. = FALSE)
}

env_integer <- function(name, default, minimum = 1L) {
    value <- suppressWarnings(as.integer(Sys.getenv(name, as.character(default))))
    if (length(value) != 1L || !is.finite(value) || value < minimum) {
        stop(name, " must be an integer at least ", minimum, ".", call. = FALSE)
    }
    value
}

env_numeric <- function(name, default, lower = -Inf, upper = Inf) {
    value <- suppressWarnings(as.numeric(Sys.getenv(name, as.character(default))))
    if (length(value) != 1L || !is.finite(value) ||
        value < lower || value > upper) {
        stop(
            name, " must be finite and lie in [",
            format(lower), ", ", format(upper), "].",
            call. = FALSE
        )
    }
    value
}

physical_cores <- suppressWarnings(parallel::detectCores(logical = FALSE))
if (!is.finite(physical_cores) || physical_cores < 1L) physical_cores <- 1L
requested_cores <- env_integer(
    "DASRA_ABUND_CORES",
    min(8L, physical_cores),
    minimum = 1L
)

CONFIG <- list(
    script_version = "2026-08-18-present-conditional-abundance-v3-maaslin3-extraction-fix",
    n_rep = env_integer("DASRA_ABUND_REPS", 30L),
    n_per_group = env_integer("DASRA_ABUND_N_PER_GROUP", 100L, minimum = 30L),
    n_taxa = env_integer("DASRA_ABUND_TAXA", 30L, minimum = 20L),
    n_cores = max(1L, min(8L, requested_cores, physical_cores)),
    alpha = env_numeric("DASRA_ABUND_ALPHA", 0.05, 0, 1),
    base_seed = env_integer("DASRA_ABUND_SEED", 20260818L),
    output_dir = Sys.getenv(
        "DASRA_ABUND_OUTDIR",
        file.path(getwd(), "dasra_present_conditional_abundance_simulation")
    ),
    resume = env_flag("DASRA_ABUND_RESUME", TRUE),
    include_heavy_tail = env_flag("DASRA_ABUND_HEAVY_TAIL", FALSE),

    # Numerical settings for the proposed method.
    quadrature_order = env_integer("DASRA_ABUND_Q", 41L, minimum = 11L),
    effect_quadrature_order = 41L,
    root_tolerance = 1e-5,
    jacobian_condition_limit = 1e10,
    parameter_boundary_tolerance = 1e-5,

    # Sequencing-depth distribution.
    depth_median = 8000,
    depth_sdlog = 0.45,
    depth_min = 1500L,
    depth_max = 40000L,
    depth_imbalance_multiplier = 0.45,

    # Latent positive-abundance distribution.
    abundance_sd_min = 0.40,
    abundance_sd_max = 0.75,
    sample_factor_sd = 0.70,
    loading_sd = 0.28,
    covariate_group_shift = 0.30,

    # Signal settings.
    balanced_abundance_effect = 0.75,
    rare_abundance_effect = 1.00,
    rare_baseline_multiplier = 0.15,
    rare_structural_log_odds_offset = -0.80,
    sparse_unidirectional_effect = 0.85,
    dense_unidirectional_effect = 0.55,
    structural_log_odds_effect = 1.15,

    # Competitor settings.
    zinq_taus = c(0.25, 0.50, 0.75),
    maaslin3_median_comparison = TRUE
)

validate_config <- function(config) {
    stopifnot(
        config$n_rep >= 1L,
        config$n_per_group >= 30L,
        config$n_taxa >= 20L,
        config$n_cores >= 1L,
        config$n_cores <= 8L,
        config$alpha > 0,
        config$alpha < 1,
        config$quadrature_order >= 11L,
        config$effect_quadrature_order >= 11L,
        config$rare_baseline_multiplier > 0,
        config$rare_baseline_multiplier < 1,
        config$depth_imbalance_multiplier > 0,
        config$depth_imbalance_multiplier < 1
    )
    invisible(TRUE)
}
validate_config(CONFIG)

SCENARIOS <- data.frame(
    scenario = c(
        "global_null",
        "depth_imbalanced_null",
        "balanced_abundance",
        "rare_present_abundance",
        "sparse_unidirectional",
        "dense_unidirectional",
        "structural_only",
        "mixed_structural_abundance"
    ),
    label = c(
        "Global null",
        "Depth-imbalanced null",
        "Balanced abundance",
        "Rare present abundance",
        "Sparse unidirectional abundance",
        "Dense unidirectional abundance",
        "Structural absence only",
        "Mixed structural + abundance"
    ),
    stringsAsFactors = FALSE
)

DGP_VARIANTS <- if (isTRUE(CONFIG$include_heavy_tail)) {
    c("lognormal", "heavy_tail")
} else {
    "lognormal"
}

required_packages <- c(
    "ZINQ", "maaslin3", "nleqslv", "statmod",
    "ggplot2", "dplyr", "tidyr"
)
missing_packages <- required_packages[
    !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]
if (length(missing_packages)) {
    stop(
        "Install the following package(s) before running the script: ",
        paste(missing_packages, collapse = ", "),
        call. = FALSE
    )
}

suppressPackageStartupMessages({
    library(ggplot2)
    library(dplyr)
    library(tidyr)
})

dir.create(CONFIG$output_dir, recursive = TRUE, showWarnings = FALSE)
checkpoint_dir <- file.path(CONFIG$output_dir, "replicate_checkpoints")
dir.create(checkpoint_dir, recursive = TRUE, showWarnings = FALSE)

# =============================================================================
# General numerical utilities
# =============================================================================

clamp <- function(x, lower, upper) {
    pmin(pmax(x, lower), upper)
}

softplus <- function(x) {
    pmax(x, 0) + log1p(exp(-abs(x)))
}

log_plogis <- function(x) {
    -softplus(-x)
}

row_log_sum_exp <- function(x) {
    x <- as.matrix(x)
    maximum <- apply(x, 1L, max)
    output <- maximum + log(rowSums(exp(x - maximum)))
    bad <- !is.finite(maximum)
    output[bad] <- maximum[bad]
    output
}

log1mexp <- function(log_x) {
    log_x <- as.numeric(log_x)
    if (any(log_x > 1e-12, na.rm = TRUE)) {
        stop("log1mexp requires log_x <= 0.", call. = FALSE)
    }
    log_x <- pmin(log_x, 0)
    cutoff <- -log(2)
    output <- numeric(length(log_x))
    near_zero <- log_x > cutoff
    output[near_zero] <- log(-expm1(log_x[near_zero]))
    output[!near_zero] <- log1p(-exp(log_x[!near_zero]))
    output
}

safe_mean <- function(x) {
    if (!length(x) || all(is.na(x))) return(NA_real_)
    mean(x, na.rm = TRUE)
}

safe_sd <- function(x) {
    x <- x[is.finite(x)]
    if (length(x) < 2L) return(NA_real_)
    stats::sd(x)
}

collapse_conditions <- function(x) {
    x <- unique(trimws(as.character(x)))
    x <- x[nzchar(x)]
    if (!length(x)) NA_character_ else paste(x, collapse = " | ")
}

object_fingerprint <- function(object) {
    path <- tempfile(fileext = ".rds")
    on.exit(unlink(path), add = TRUE)
    saveRDS(object, path, version = 3)
    unname(tools::md5sum(path))
}

script_fingerprint <- function() {
    args <- commandArgs(trailingOnly = FALSE)
    file_arg <- grep("^--file=", args, value = TRUE)
    if (!length(file_arg)) return(NA_character_)
    path <- sub("^--file=", "", file_arg[1L])
    if (!file.exists(path)) return(NA_character_)
    unname(tools::md5sum(path))
}

numeric_gradient <- function(par, fn, lower = rep(-Inf, length(par)),
                             upper = rep(Inf, length(par))) {
    par <- as.numeric(par)
    gradient <- numeric(length(par))
    f0 <- fn(par)
    for (k in seq_along(par)) {
        step <- 1e-4 * (1 + abs(par[k]))
        left_ok <- par[k] - step > lower[k]
        right_ok <- par[k] + step < upper[k]
        if (left_ok && right_ok) {
            left <- right <- par
            left[k] <- par[k] - step
            right[k] <- par[k] + step
            gradient[k] <- (fn(right) - fn(left)) / (2 * step)
        } else if (right_ok) {
            right <- par
            right[k] <- par[k] + step
            gradient[k] <- (fn(right) - f0) / step
        } else if (left_ok) {
            left <- par
            left[k] <- par[k] - step
            gradient[k] <- (f0 - fn(left)) / step
        } else {
            gradient[k] <- NA_real_
        }
    }
    gradient
}

numeric_jacobian <- function(par, fn, lower = rep(-Inf, length(par)),
                             upper = rep(Inf, length(par))) {
    par <- as.numeric(par)
    f0 <- as.numeric(fn(par))
    jacobian <- matrix(NA_real_, nrow = length(f0), ncol = length(par))
    for (k in seq_along(par)) {
        step <- 1e-4 * (1 + abs(par[k]))
        left_ok <- par[k] - step > lower[k]
        right_ok <- par[k] + step < upper[k]
        if (left_ok && right_ok) {
            left <- right <- par
            left[k] <- par[k] - step
            right[k] <- par[k] + step
            jacobian[, k] <- (fn(right) - fn(left)) / (2 * step)
        } else if (right_ok) {
            right <- par
            right[k] <- par[k] + step
            jacobian[, k] <- (fn(right) - f0) / step
        } else if (left_ok) {
            left <- par
            left[k] <- par[k] - step
            jacobian[, k] <- (f0 - fn(left)) / step
        }
    }
    jacobian
}

matrix_condition_number <- function(x) {
    singular_values <- tryCatch(
        svd(x, nu = 0, nv = 0)$d,
        error = function(e) numeric()
    )
    if (!length(singular_values) || any(!is.finite(singular_values)) ||
        min(singular_values) <= 0) {
        return(Inf)
    }
    max(singular_values) / min(singular_values)
}

# =============================================================================
# Gauss-Hermite integration for the prototype abundance method
# =============================================================================

make_normal_gh_rule <- function(order) {
    rule <- statmod::gauss.quad(as.integer(order), kind = "hermite")
    node <- as.numeric(rule$nodes)
    raw_weight <- as.numeric(rule$weights)
    weight <- raw_weight / sum(raw_weight)
    list(
        order = as.integer(order),
        node = node,
        z = sqrt(2) * node,
        raw_weight = raw_weight,
        log_raw_weight = log(raw_weight),
        weight = weight,
        log_weight = log(weight)
    )
}

GH_FIT <- make_normal_gh_rule(CONFIG$quadrature_order)
GH_EFFECT <- make_normal_gh_rule(CONFIG$effect_quadrature_order)

latent_mode <- function(y, N, eta, sigma, maxit = 80L) {
    sigma2 <- sigma^2
    prior_precision <- 1 / sigma2
    pseudo_probability <- clamp(
        (y + 0.5) / (N + 1), 1e-12, 1 - 1e-12
    )
    x <- (
        qlogis(pseudo_probability) + prior_precision * eta
    ) / (1 + prior_precision)
    lower <- eta - sigma2 * (N - y)
    upper <- eta + sigma2 * y
    x <- clamp(x, lower, upper)

    for (iteration in seq_len(maxit)) {
        p <- plogis(x)
        score <- y - N * p - (x - eta) * prior_precision
        curvature <- N * p * (1 - p) + prior_precision
        positive_score <- score > 0
        lower[positive_score] <- x[positive_score]
        upper[!positive_score] <- x[!positive_score]

        newton <- x + score / curvature
        midpoint <- lower + 0.5 * (upper - lower)
        use_newton <- is.finite(newton) &
            newton > lower & newton < upper &
            abs(newton - x) <= 0.5 * (upper - lower)
        next_x <- ifelse(use_newton, newton, midpoint)
        converged <- abs(score / curvature) <= 1e-12 * (1 + abs(x)) |
            abs(upper - lower) <= 1e-12 * (1 + abs(x))
        next_x[converged] <- x[converged]
        x <- next_x
        if (all(converged)) break
    }

    p <- plogis(x)
    score <- y - N * p - (x - eta) * prior_precision
    curvature <- N * p * (1 - p) + prior_precision
    if (any(!is.finite(x)) || any(!is.finite(curvature)) ||
        any(curvature <= 0) ||
        any(abs(score / curvature) > 1e-8 * (1 + abs(x)))) {
        stop("Adaptive latent-mode solver failed.", call. = FALSE)
    }
    list(mode = x, curvature = curvature)
}

gh_binomial_marginal <- function(y, N, eta, sigma, gh, need_posterior = TRUE) {
    y <- as.numeric(y)
    N <- as.numeric(N)
    eta <- as.numeric(eta)
    n <- length(y)
    if (length(N) != n || length(eta) != n ||
        !is.finite(sigma) || sigma <= 0) {
        stop("Invalid inputs to gh_binomial_marginal.", call. = FALSE)
    }

    mode_information <- latent_mode(y, N, eta, sigma)
    mode <- mode_information$mode
    curvature <- mode_information$curvature
    q <- length(gh$node)
    scale <- sqrt(2 / curvature)

    x <- matrix(mode, nrow = n, ncol = q) +
        matrix(scale, nrow = n, ncol = q) *
        matrix(gh$node, nrow = n, ncol = q, byrow = TRUE)
    centered <- x - matrix(eta, nrow = n, ncol = q)

    log_kernel <- sweep(x, 1L, y, "*") -
        sweep(softplus(x), 1L, N, "*") -
        sweep(centered^2, 1L, rep(2 * sigma^2, n), "/") -
        log(sigma) - 0.5 * log(2 * pi)
    log_terms <- log_kernel +
        matrix(gh$node^2, nrow = n, ncol = q, byrow = TRUE) +
        matrix(
            gh$log_raw_weight, nrow = n, ncol = q, byrow = TRUE
        )
    log_normalizer <- row_log_sum_exp(log_terms)
    log_choose <- lgamma(N + 1) - lgamma(y + 1) - lgamma(N - y + 1)
    log_h <- log_choose + 0.5 * log(2 / curvature) + log_normalizer

    if (!isTRUE(need_posterior)) {
        return(list(log_h = log_h))
    }

    posterior_weight <- exp(log_terms - log_normalizer)
    posterior_m1 <- rowSums(posterior_weight * centered)
    posterior_m2 <- rowSums(posterior_weight * centered^2)

    list(
        log_h = log_h,
        posterior_weight = posterior_weight,
        score_eta = posterior_m1 / sigma^2,
        score_omega = posterior_m2 / sigma^2 - 1,
        posterior_m1 = posterior_m1,
        posterior_m2 = posterior_m2,
        posterior_mean_x = rowSums(posterior_weight * x),
        posterior_mean_log_q = rowSums(
            posterior_weight * (-softplus(-x))
        )
    )
}

normal_mean_log_relative <- function(location, sigma, gh = GH_EFFECT) {
    location <- as.numeric(location)
    x <- matrix(location, nrow = length(location), ncol = length(gh$z)) +
        sigma * matrix(
            gh$z, nrow = length(location), ncol = length(gh$z),
            byrow = TRUE
        )
    as.numeric((-softplus(-x)) %*% gh$weight)
}

# =============================================================================
# Proposed DASRA abundance estimating equations
# =============================================================================

make_design_matrices <- function(group, z) {
    group <- as.numeric(group)
    z <- as.matrix(z)
    if (!ncol(z)) {
        X_b <- matrix(1, nrow = length(group), ncol = 1L)
        X_rho <- cbind(Intercept = 1, Group = group)
        X_full <- cbind(Intercept = 1, Group = group)
    } else {
        X_b <- cbind(Intercept = 1, z)
        colnames(X_b) <- c("Intercept", paste0("z", seq_len(ncol(z))))
        X_rho <- cbind(Intercept = 1, Group = group, z)
        colnames(X_rho) <- c(
            "Intercept", "Group", paste0("z", seq_len(ncol(z)))
        )
        X_full <- X_rho
    }
    list(X_b = X_b, X_rho = X_rho, X_full = X_full)
}

proposed_parameter_layout <- function(X_b, X_rho) {
    nb <- ncol(X_b)
    na <- ncol(X_rho)
    list(
        nb = nb,
        na = na,
        b = seq_len(nb),
        omega = nb + 1L,
        a = nb + 1L + seq_len(na),
        zeta = nb + na + 2L,
        dimension = nb + na + 2L
    )
}

proposed_parameter_bounds <- function(layout) {
    lower <- upper <- rep(NA_real_, layout$dimension)

    lower[layout$b] <- c(-20, rep(-5, layout$nb - 1L))
    upper[layout$b] <- c(5, rep(5, layout$nb - 1L))
    lower[layout$omega] <- log(0.15)
    upper[layout$omega] <- log(4)
    lower[layout$a] <- -10
    upper[layout$a] <- 10
    lower[layout$zeta] <- -5
    upper[layout$zeta] <- 5

    list(lower = lower, upper = upper)
}

proposed_state <- function(theta, data, gh = GH_FIT, return_psi = TRUE) {
    layout <- data$layout
    b <- theta[layout$b]
    omega <- theta[layout$omega]
    a <- theta[layout$a]
    zeta <- theta[layout$zeta]

    sigma <- exp(omega)
    eta <- as.numeric(data$X_b %*% b + zeta * data$group)
    lp_rho <- as.numeric(data$X_rho %*% a)
    rho <- clamp(plogis(lp_rho), 1e-10, 1 - 1e-10)

    marginal_y <- gh_binomial_marginal(
        y = data$y,
        N = data$N,
        eta = eta,
        sigma = sigma,
        gh = gh,
        need_posterior = TRUE
    )
    marginal_0 <- gh_binomial_marginal(
        y = rep(0, length(data$y)),
        N = data$N,
        eta = eta,
        sigma = sigma,
        gh = gh,
        need_posterior = TRUE
    )

    log_h0 <- pmin(marginal_0$log_h, -1e-12)
    h0 <- clamp(exp(log_h0), 0, 1 - 1e-12)
    r <- 1 - h0
    if (any(!is.finite(r)) || any(r <= 1e-12)) {
        stop("Conditional detection probability is numerically degenerate.")
    }

    positive <- data$y > 0
    gamma <- numeric(length(data$y))
    zero <- !positive
    if (any(zero)) {
        gamma[zero] <- plogis(qlogis(rho[zero]) - log_h0[zero])
    }
    presence_weight <- 1 - gamma

    if (!isTRUE(return_psi)) {
        return(list(
            eta = eta,
            sigma = sigma,
            rho = rho,
            gamma = gamma,
            presence_weight = presence_weight,
            h0 = h0,
            r = r,
            marginal_y = marginal_y,
            marginal_0 = marginal_0
        ))
    }

    n <- length(data$y)
    mark_eta <- numeric(n)
    mark_omega <- numeric(n)
    if (any(positive)) {
        ratio <- h0[positive] / r[positive]
        mark_eta[positive] <- marginal_y$score_eta[positive] +
            ratio * marginal_0$score_eta[positive]
        mark_omega[positive] <- marginal_y$score_omega[positive] +
            ratio * marginal_0$score_omega[positive]
    }

    psi_b <- data$X_b * mark_eta
    psi_omega <- mark_omega
    psi_a <- data$X_rho * (gamma - rho)
    psi_zeta <- data$group * presence_weight * marginal_y$score_eta

    psi <- cbind(psi_b, omega = psi_omega, psi_a, zeta = psi_zeta)

    list(
        eta = eta,
        sigma = sigma,
        rho = rho,
        gamma = gamma,
        presence_weight = presence_weight,
        h0 = h0,
        r = r,
        marginal_y = marginal_y,
        marginal_0 = marginal_0,
        psi = psi
    )
}

fit_positive_mark_initial <- function(data, gh = GH_FIT) {
    positive <- data$y > 0
    if (sum(positive) <= ncol(data$X_full) + 1L ||
        qr(data$X_full[positive, , drop = FALSE])$rank <
            ncol(data$X_full)) {
        return(NULL)
    }

    X <- data$X_full
    y <- data$y
    N <- data$N

    objective <- function(par) {
        coefficient <- par[seq_len(ncol(X))]
        sigma <- exp(par[ncol(X) + 1L])
        eta <- as.numeric(X %*% coefficient)
        marginal_y <- gh_binomial_marginal(
            y[positive], N[positive], eta[positive], sigma, gh,
            need_posterior = FALSE
        )
        marginal_0 <- gh_binomial_marginal(
            rep(0, sum(positive)), N[positive], eta[positive], sigma, gh,
            need_posterior = FALSE
        )
        if (any(marginal_0$log_h >= -1e-12)) return(1e8)
        log_r <- log1mexp(marginal_0$log_h)
        value <- -mean(marginal_y$log_h - log_r)
        if (is.finite(value)) value else 1e8
    }

    observed_logit <- qlogis(clamp(
        (y[positive] + 0.5) / (N[positive] + 1),
        1e-8, 1 - 1e-8
    ))
    coefficient_start <- tryCatch(
        as.numeric(qr.solve(
            data$X_full[positive, , drop = FALSE],
            observed_logit
        )),
        error = function(e) rep(0, ncol(data$X_full))
    )
    coefficient_start[!is.finite(coefficient_start)] <- 0
    coefficient_start[1L] <- clamp(coefficient_start[1L], -20, 5)
    if (length(coefficient_start) > 1L) {
        coefficient_start[-1L] <- clamp(coefficient_start[-1L], -5, 5)
    }

    residual <- observed_logit -
        as.numeric(data$X_full[positive, , drop = FALSE] %*%
                       coefficient_start)
    sigma_start <- clamp(stats::sd(residual), 0.3, 2)
    if (!is.finite(sigma_start)) sigma_start <- 1

    starts <- lapply(c(0.5, sigma_start, 1, 1.5), function(s) {
        c(coefficient_start, log(s))
    })
    starts[[length(starts) + 1L]] <- c(
        c(mean(observed_logit), rep(0, ncol(X) - 1L)),
        log(1)
    )

    lower <- c(-20, rep(-5, ncol(X) - 1L), log(0.15))
    upper <- c(5, rep(5, ncol(X) - 1L), log(4))

    fits <- lapply(starts, function(start) {
        start <- clamp(start, lower, upper)
        tryCatch(
            optim(
                start, objective, method = "L-BFGS-B",
                lower = lower, upper = upper,
                control = list(maxit = 300L, factr = 1e7)
            ),
            error = function(e) NULL
        )
    })
    valid <- vapply(fits, function(fit) {
        !is.null(fit) && is.finite(fit$value) &&
            all(is.finite(fit$par))
    }, logical(1))
    if (!any(valid)) return(NULL)
    candidates <- fits[valid]
    candidates[[which.min(vapply(candidates, `[[`, numeric(1), "value"))]]
}

fit_detection_initial <- function(data, b, omega, zeta, gh = GH_FIT) {
    sigma <- exp(omega)
    eta <- as.numeric(data$X_b %*% b + zeta * data$group)
    marginal_0 <- gh_binomial_marginal(
        rep(0, length(data$y)), data$N, eta, sigma, gh,
        need_posterior = FALSE
    )
    if (any(marginal_0$log_h >= -1e-12)) return(NULL)
    r <- 1 - exp(marginal_0$log_h)
    detected <- as.numeric(data$y > 0)

    objective <- function(a) {
        rho <- clamp(plogis(as.numeric(data$X_rho %*% a)), 1e-10, 1 - 1e-10)
        q <- clamp((1 - rho) * r, 1e-12, 1 - 1e-12)
        value <- -mean(detected * log(q) + (1 - detected) * log1p(-q))
        if (is.finite(value)) value else 1e8
    }

    observed_zero <- mean(data$y == 0)
    starts <- lapply(c(0.10, 0.30, 0.50, 0.70), function(multiplier) {
        probability <- clamp(multiplier * max(observed_zero, 0.05), 0.01, 0.90)
        c(qlogis(probability), rep(0, ncol(data$X_rho) - 1L))
    })

    fits <- lapply(starts, function(start) {
        tryCatch(
            optim(
                start, objective, method = "L-BFGS-B",
                lower = rep(-10, length(start)),
                upper = rep(10, length(start)),
                control = list(maxit = 300L, factr = 1e7)
            ),
            error = function(e) NULL
        )
    })
    valid <- vapply(fits, function(fit) {
        !is.null(fit) && is.finite(fit$value) &&
            all(is.finite(fit$par))
    }, logical(1))
    if (!any(valid)) return(NULL)
    candidates <- fits[valid]
    candidates[[which.min(vapply(candidates, `[[`, numeric(1), "value"))]]
}

proposed_delta <- function(theta, data, gh_effect = GH_EFFECT) {
    layout <- data$layout
    b <- theta[layout$b]
    sigma <- exp(theta[layout$omega])
    zeta <- theta[layout$zeta]
    baseline <- as.numeric(data$X_b %*% b)
    mean(
        normal_mean_log_relative(baseline + zeta, sigma, gh_effect) -
            normal_mean_log_relative(baseline, sigma, gh_effect)
    )
}

empty_proposed_fit <- function(status) {
    list(
        available = FALSE,
        status = status,
        theta = NULL,
        raw_delta = NA_real_,
        raw_se = NA_real_,
        raw_p = NA_real_,
        phi = NULL,
        score_residue = NA_real_,
        jacobian_condition = NA_real_
    )
}

fit_proposed_taxon <- function(y, N, group, z,
                               gh_fit = GH_FIT,
                               gh_effect = GH_EFFECT,
                               config = CONFIG) {
    y <- as.numeric(y)
    N <- as.numeric(N)
    group <- as.numeric(group)
    z <- as.matrix(z)
    n <- length(y)

    if (length(N) != n || length(group) != n || nrow(z) != n ||
        any(!is.finite(y)) || any(!is.finite(N)) ||
        any(y < 0) || any(N <= 0) || any(y > N)) {
        return(empty_proposed_fit("invalid_input"))
    }

    design <- make_design_matrices(group, z)
    positive <- y > 0
    if (sum(positive) < 3L) {
        return(empty_proposed_fit("fewer_than_three_positive_counts"))
    }
    if (length(unique(group[positive])) < 2L) {
        return(empty_proposed_fit("positive_counts_in_one_group_only"))
    }
    if (qr(design$X_full)$rank < ncol(design$X_full) ||
        qr(design$X_rho)$rank < ncol(design$X_rho) ||
        qr(design$X_full[positive, , drop = FALSE])$rank <
            ncol(design$X_full)) {
        return(empty_proposed_fit("rank_deficient_design"))
    }

    layout <- proposed_parameter_layout(design$X_b, design$X_rho)
    bounds <- proposed_parameter_bounds(layout)
    data <- list(
        y = y,
        N = N,
        group = group,
        z = z,
        X_b = design$X_b,
        X_rho = design$X_rho,
        X_full = design$X_full,
        layout = layout
    )

    mark_fit <- fit_positive_mark_initial(data, gh_fit)
    if (is.null(mark_fit)) {
        return(empty_proposed_fit("positive_mark_initialization_failed"))
    }

    full_coefficient <- mark_fit$par[seq_len(ncol(design$X_full))]
    b_start <- c(full_coefficient[1L], full_coefficient[-c(1L, 2L)])
    if (ncol(design$X_full) == 2L) b_start <- full_coefficient[1L]
    zeta_start <- full_coefficient[2L]
    omega_start <- mark_fit$par[ncol(design$X_full) + 1L]

    detection_fit <- fit_detection_initial(
        data = data,
        b = b_start,
        omega = omega_start,
        zeta = zeta_start,
        gh = gh_fit
    )
    if (is.null(detection_fit)) {
        return(empty_proposed_fit("detection_initialization_failed"))
    }

    theta_start <- numeric(layout$dimension)
    theta_start[layout$b] <- b_start
    theta_start[layout$omega] <- omega_start
    theta_start[layout$a] <- detection_fit$par
    theta_start[layout$zeta] <- zeta_start
    theta_start <- clamp(theta_start, bounds$lower, bounds$upper)

    initial_state <- tryCatch(
        proposed_state(theta_start, data, gh_fit, return_psi = TRUE),
        error = function(e) NULL
    )
    if (is.null(initial_state)) {
        return(empty_proposed_fit("initial_estimating_equations_failed"))
    }
    equation_scale <- sqrt(colMeans(initial_state$psi^2))
    equation_scale[!is.finite(equation_scale) | equation_scale < 1e-3] <- 1

    equation_mean <- function(theta) {
        state <- tryCatch(
            proposed_state(theta, data, gh_fit, return_psi = TRUE),
            error = function(e) NULL
        )
        if (is.null(state)) {
            return(rep(1e3, layout$dimension))
        }
        colMeans(state$psi)
    }
    equation_scaled <- function(theta) {
        equation_mean(theta) / equation_scale
    }

    candidates <- list(theta_start)

    root_1 <- tryCatch(
        nleqslv::nleqslv(
            theta_start,
            equation_scaled,
            method = "Broyden",
            global = "dbldog",
            control = list(
                ftol = 1e-9,
                xtol = 1e-9,
                maxit = 150L,
                allowSingular = FALSE
            )
        ),
        error = function(e) NULL
    )
    if (!is.null(root_1) && all(is.finite(root_1$x))) {
        candidates[[length(candidates) + 1L]] <- root_1$x
    }

    best_before_optim <- candidates[[which.min(vapply(candidates, function(x) {
        value <- equation_scaled(x)
        if (any(!is.finite(value))) Inf else sum(value^2)
    }, numeric(1)))]]
    best_before_optim <- clamp(
        best_before_optim, bounds$lower, bounds$upper
    )

    score_objective <- function(theta) {
        value <- equation_scaled(theta)
        if (any(!is.finite(value))) return(1e12)
        sum(value^2) / 2
    }
    squared_fit <- tryCatch(
        optim(
            best_before_optim,
            score_objective,
            method = "L-BFGS-B",
            lower = bounds$lower,
            upper = bounds$upper,
            control = list(maxit = 500L, factr = 1e7)
        ),
        error = function(e) NULL
    )
    if (!is.null(squared_fit) && is.finite(squared_fit$value) &&
        all(is.finite(squared_fit$par))) {
        candidates[[length(candidates) + 1L]] <- squared_fit$par
        root_2 <- tryCatch(
            nleqslv::nleqslv(
                squared_fit$par,
                equation_scaled,
                method = "Newton",
                global = "dbldog",
                control = list(
                    ftol = 1e-10,
                    xtol = 1e-10,
                    maxit = 100L,
                    allowSingular = FALSE
                )
            ),
            error = function(e) NULL
        )
        if (!is.null(root_2) && all(is.finite(root_2$x))) {
            candidates[[length(candidates) + 1L]] <- root_2$x
        }
    }

    candidate_metric <- vapply(candidates, function(theta) {
        if (any(theta < bounds$lower) || any(theta > bounds$upper)) return(Inf)
        value <- equation_mean(theta)
        if (any(!is.finite(value))) Inf else max(abs(value))
    }, numeric(1))
    if (!any(is.finite(candidate_metric))) {
        return(empty_proposed_fit("estimating_equation_solver_failed"))
    }

    theta_hat <- candidates[[which.min(candidate_metric)]]
    residue <- min(candidate_metric)
    if (!is.finite(residue) || residue > config$root_tolerance) {
        return(empty_proposed_fit("estimating_equation_residue"))
    }

    boundary_distance <- pmin(
        theta_hat - bounds$lower,
        bounds$upper - theta_hat
    )
    if (any(boundary_distance <= config$parameter_boundary_tolerance)) {
        return(empty_proposed_fit("parameter_on_boundary"))
    }

    fitted_state <- tryCatch(
        proposed_state(theta_hat, data, gh_fit, return_psi = TRUE),
        error = function(e) NULL
    )
    if (is.null(fitted_state) || any(!is.finite(fitted_state$psi))) {
        return(empty_proposed_fit("fitted_state_failed"))
    }

    jacobian_mean <- numeric_jacobian(
        theta_hat, equation_mean,
        lower = bounds$lower, upper = bounds$upper
    )
    condition <- matrix_condition_number(jacobian_mean)
    if (any(!is.finite(jacobian_mean)) ||
        !is.finite(condition) ||
        condition > config$jacobian_condition_limit) {
        return(empty_proposed_fit("singular_or_ill_conditioned_jacobian"))
    }

    delta_hat <- proposed_delta(theta_hat, data, gh_effect)
    delta_gradient <- numeric_gradient(
        theta_hat,
        function(theta) proposed_delta(theta, data, gh_effect),
        lower = bounds$lower,
        upper = bounds$upper
    )
    if (!is.finite(delta_hat) || any(!is.finite(delta_gradient))) {
        return(empty_proposed_fit("effect_gradient_failed"))
    }

    A_sum <- n * jacobian_mean
    parameter_contribution <- tryCatch(
        solve(A_sum, t(fitted_state$psi)),
        error = function(e) NULL
    )
    if (is.null(parameter_contribution) ||
        any(!is.finite(parameter_contribution))) {
        return(empty_proposed_fit("influence_solve_failed"))
    }

    phi <- -as.numeric(delta_gradient %*% parameter_contribution)
    raw_variance <- sum(phi^2)
    if (!is.finite(raw_variance) || raw_variance <= 0) {
        return(empty_proposed_fit("nonpositive_raw_variance"))
    }

    raw_se <- sqrt(raw_variance)
    raw_z <- delta_hat / raw_se
    raw_p <- 2 * pnorm(-abs(raw_z))

    list(
        available = TRUE,
        status = "ok",
        theta = theta_hat,
        raw_delta = delta_hat,
        raw_se = raw_se,
        raw_p = raw_p,
        phi = phi,
        score_residue = residue,
        jacobian_condition = condition,
        mean_presence_weight = mean(fitted_state$presence_weight),
        mean_zero_presence_weight = if (any(y == 0)) {
            mean(fitted_state$presence_weight[y == 0])
        } else {
            NA_real_
        }
    )
}


intercept_lts_pilot <- function(values) {
    values <- as.numeric(values)
    values <- values[is.finite(values)]
    m <- length(values)
    if (m < 3L) return(NA_real_)

    # A strict majority is retained. For an intercept-only least-trimmed-
    # squares problem in one dimension, an optimal subset is contiguous after
    # sorting. Ties are resolved by the first minimizing interval, making the
    # pilot deterministic.
    h <- floor(m / 2L) + 1L
    ordered <- sort(values)
    cumulative <- c(0, cumsum(ordered))
    cumulative_square <- c(0, cumsum(ordered^2))
    starts <- seq_len(m - h + 1L)
    sums <- cumulative[starts + h] - cumulative[starts]
    sums_square <- cumulative_square[starts + h] -
        cumulative_square[starts]
    sse <- sums_square - sums^2 / h
    best <- starts[which.min(sse)]
    mean(ordered[best:(best + h - 1L)])
}

compositionally_correct_proposed <- function(fits, truth, n_samples) {
    p <- length(fits)
    raw_delta <- vapply(fits, function(x) x$raw_delta, numeric(1))
    raw_se <- vapply(fits, function(x) x$raw_se, numeric(1))
    available <- vapply(fits, function(x) isTRUE(x$available), logical(1))

    output <- data.frame(
        target = truth$target,
        method = "DASRA proposed abundance",
        p_value = NA_real_,
        estimate = NA_real_,
        standard_error = NA_real_,
        available = FALSE,
        status = ifelse(available, "background_unavailable",
                        vapply(fits, `[[`, character(1), "status")),
        background_size = NA_integer_,
        background_pilot = NA_real_,
        background_estimate = NA_real_,
        background_reference_fraction = NA_real_,
        raw_estimate = raw_delta,
        raw_standard_error = raw_se,
        raw_p_value = vapply(fits, function(x) x$raw_p, numeric(1)),
        score_residue = vapply(fits, function(x) x$score_residue, numeric(1)),
        jacobian_condition = vapply(
            fits, function(x) x$jacobian_condition, numeric(1)
        ),
        mean_presence_weight = vapply(
            fits,
            function(x) x$mean_presence_weight %||% NA_real_,
            numeric(1)
        ),
        mean_zero_presence_weight = vapply(
            fits,
            function(x) x$mean_zero_presence_weight %||% NA_real_,
            numeric(1)
        ),
        stringsAsFactors = FALSE
    )

    eligible <- which(available & is.finite(raw_delta) & is.finite(raw_se) &
                          raw_se > 0)
    if (length(eligible) < 5L) {
        return(output)
    }

    phi_matrix <- matrix(NA_real_, nrow = n_samples, ncol = p)
    for (j in eligible) phi_matrix[, j] <- fits[[j]]$phi

    threshold <- sqrt(2 * log(max(n_samples * length(eligible), 3)))

    for (j in eligible) {
        others <- setdiff(eligible, j)
        if (length(others) < 3L) next

        pilot <- intercept_lts_pilot(raw_delta[others])
        if (!is.finite(pilot)) {
            output$status[j] <- "background_pilot_unavailable"
            next
        }
        studentized <- abs(raw_delta[others] - pilot) /
            pmax(raw_se[others], 1e-10)
        reference <- others[studentized <= threshold]

        if (length(reference) < 3L) {
            output$status[j] <- "fewer_than_three_reference_taxa"
            next
        }

        background <- mean(raw_delta[reference])
        phi_background <- rowMeans(phi_matrix[, reference, drop = FALSE])
        corrected_phi <- phi_matrix[, j] - phi_background
        variance <- sum(corrected_phi^2)

        if (!is.finite(variance) || variance <= 0) {
            output$status[j] <- "nonpositive_corrected_variance"
            next
        }

        corrected <- raw_delta[j] - background
        se <- sqrt(variance)
        p_value <- 2 * pnorm(-abs(corrected / se))

        output$p_value[j] <- p_value
        output$estimate[j] <- corrected
        output$standard_error[j] <- se
        output$available[j] <- is.finite(p_value)
        output$status[j] <- if (output$available[j]) "ok" else "nonfinite_p_value"
        output$background_size[j] <- length(reference)
        output$background_pilot[j] <- pilot
        output$background_estimate[j] <- background
        output$background_reference_fraction[j] <- mean(
            !truth$abundance_alt[reference]
        )
    }

    output
}

run_proposed_method <- function(sim, config) {
    p <- ncol(sim$counts)
    fits <- vector("list", p)
    for (j in seq_len(p)) {
        if (!sim$truth$retained[j]) {
            fits[[j]] <- empty_proposed_fit("not_in_common_family")
            next
        }
        fits[[j]] <- tryCatch(
            fit_proposed_taxon(
                y = sim$counts[, j],
                N = sim$depth,
                group = sim$group,
                z = sim$z,
                config = config
            ),
            error = function(e) empty_proposed_fit(
                paste0("error: ", conditionMessage(e))
            )
        )
    }
    compositionally_correct_proposed(
        fits = fits,
        truth = sim$truth,
        n_samples = nrow(sim$counts)
    )
}

# =============================================================================
# ZINQ abundance component
# =============================================================================

cauchy_combine_pvalues <- function(p_value, weight = NULL) {
    p_value <- as.numeric(p_value)
    if (!length(p_value) || any(!is.finite(p_value)) ||
        any(p_value < 0) || any(p_value > 1)) {
        return(NA_real_)
    }
    p_value <- clamp(p_value, 1e-15, 1 - 1e-15)
    if (is.null(weight)) weight <- rep(1 / length(p_value), length(p_value))
    weight <- as.numeric(weight)
    weight <- weight / sum(weight)
    statistic <- sum(weight * tan((0.5 - p_value) * pi))
    clamp(1 - pcauchy(statistic), 0, 1)
}

run_zinq_abundance <- function(sim, config, rep_id) {
    p <- ncol(sim$counts)
    rows <- vector("list", p)
    relative_abundance <- sim$counts / sim$depth
    tau_weight <- ifelse(
        config$zinq_taus <= 0.5,
        config$zinq_taus,
        1 - config$zinq_taus
    )
    tau_weight <- tau_weight / sum(tau_weight)

    for (j in seq_len(p)) {
        if (!sim$truth$retained[j]) {
            rows[[j]] <- data.frame(
                target = sim$truth$target[j],
                method = "ZINQ quantile abundance",
                p_value = NA_real_,
                estimate = NA_real_,
                standard_error = NA_real_,
                available = FALSE,
                status = "not_in_common_family",
                stringsAsFactors = FALSE
            )
            next
        }

        dat <- data.frame(
            Y = relative_abundance[, j],
            group = sim$group,
            z = sim$z[, 1L],
            log_depth = scale(log(sim$depth))[, 1L]
        )
        warning_text <- character()
        fit <- tryCatch(
            withCallingHandlers(
                ZINQ::ZINQ_tests(
                    formula.logistic = Y ~ group + z + log_depth,
                    formula.quantile = Y ~ group + z + log_depth,
                    C = "group",
                    y_CorD = "C",
                    data = dat,
                    taus = config$zinq_taus,
                    seed = config$base_seed + rep_id * 1009L + j
                ),
                warning = function(w) {
                    warning_text <<- c(warning_text, conditionMessage(w))
                    invokeRestart("muffleWarning")
                }
            ),
            error = function(e) e
        )

        p_value <- NA_real_
        status <- "official_function_failed"
        if (!inherits(fit, "error")) {
            quantile_p <- as.numeric(fit$pvalue.quantile)
            if (length(quantile_p) == length(config$zinq_taus) &&
                all(is.finite(quantile_p)) &&
                all(quantile_p >= 0) && all(quantile_p <= 1)) {
                p_value <- cauchy_combine_pvalues(quantile_p, tau_weight)
                status <- if (is.finite(p_value)) "ok" else "combination_failed"
            }
        } else {
            status <- paste0("error: ", conditionMessage(fit))
        }

        rows[[j]] <- data.frame(
            target = sim$truth$target[j],
            method = "ZINQ quantile abundance",
            p_value = p_value,
            estimate = NA_real_,
            standard_error = NA_real_,
            available = is.finite(p_value),
            status = status,
            warning = collapse_conditions(warning_text),
            stringsAsFactors = FALSE
        )
    }
    dplyr::bind_rows(rows)
}

# =============================================================================
# MaAsLin 3 abundance component
# =============================================================================

empty_method_rows <- function(target, method, status) {
    data.frame(
        target = target,
        method = method,
        p_value = NA_real_,
        estimate = NA_real_,
        standard_error = NA_real_,
        available = FALSE,
        status = status,
        stringsAsFactors = FALSE
    )
}

extract_maaslin3_abundance <- function(fit, target_names) {
    abundance <- fit$fit_data_abundance
    results <- if (is.data.frame(abundance)) {
        abundance
    } else {
        abundance$results
    }

    if (is.null(results) || !is.data.frame(results)) {
        return(empty_method_rows(
            target_names,
            "MaAsLin 3 abundance",
            "abundance_results_unavailable"
        ))
    }

    rows <- vector("list", length(target_names))
    for (j in seq_along(target_names)) {
        target <- target_names[j]
        candidates <- results[results$feature == target, , drop = FALSE]
        if ("model" %in% names(candidates)) {
            # MaAsLin 3 labels abundance-model rows as "linear" and
            # prevalence-model rows as "logistic".  Accept "abundance" as
            # well for compatibility with versions that use component labels.
            model_label <- tolower(trimws(as.character(candidates$model)))
            candidates <- candidates[
                model_label %in% c("linear", "abundance"),
                , drop = FALSE
            ]
        }
        if ("metadata" %in% names(candidates)) {
            candidates <- candidates[
                as.character(candidates$metadata) == "group",
                , drop = FALSE
            ]
        }
        if (nrow(candidates) > 1L && "value" %in% names(candidates)) {
            preferred <- as.character(candidates$value) == "case"
            if (any(preferred, na.rm = TRUE)) {
                candidates <- candidates[which(preferred)[1L], , drop = FALSE]
            }
        }
        if (nrow(candidates) > 1L && "name" %in% names(candidates)) {
            preferred <- gsub(" ", "", as.character(candidates$name)) ==
                "groupcase"
            if (any(preferred, na.rm = TRUE)) {
                candidates <- candidates[which(preferred)[1L], , drop = FALSE]
            }
        }

        if (!nrow(candidates)) {
            rows[[j]] <- empty_method_rows(
                target, "MaAsLin 3 abundance",
                "target_abundance_row_unavailable"
            )
            next
        }

        candidate <- candidates[1L, , drop = FALSE]
        p_value <- suppressWarnings(as.numeric(candidate$pval_individual)[1L])
        coefficient <- if ("coef" %in% names(candidate)) {
            suppressWarnings(as.numeric(candidate$coef)[1L])
        } else {
            NA_real_
        }
        standard_error <- if ("stderr" %in% names(candidate)) {
            suppressWarnings(as.numeric(candidate$stderr)[1L])
        } else {
            NA_real_
        }
        error_text <- if ("error" %in% names(candidate)) {
            as.character(candidate$error)[1L]
        } else {
            NA_character_
        }
        if (is.na(error_text) || identical(error_text, "NA") ||
            !nzchar(trimws(error_text))) {
            error_text <- NA_character_
        }

        available <- is.finite(p_value) && p_value >= 0 && p_value <= 1
        rows[[j]] <- data.frame(
            target = target,
            method = "MaAsLin 3 abundance",
            p_value = if (available) p_value else NA_real_,
            estimate = coefficient,
            standard_error = standard_error,
            available = available,
            status = if (available) {
                "ok"
            } else if (!is.na(error_text)) {
                error_text
            } else {
                "nonfinite_p_value"
            },
            stringsAsFactors = FALSE
        )
    }
    dplyr::bind_rows(rows)
}

run_maaslin3_abundance <- function(sim, config, rep_id, scenario_name) {
    target_names <- sim$truth$target
    if (!any(sim$truth$retained)) {
        return(empty_method_rows(
            target_names,
            "MaAsLin 3 abundance",
            "no_taxa_in_common_family"
        ))
    }

    output_dir <- tempfile(sprintf(
        "maaslin3_abundance_%04d_%s_", rep_id, scenario_name
    ))
    on.exit({
        try(maaslin3::maaslin_log_reset(), silent = TRUE)
        unlink(output_dir, recursive = TRUE, force = TRUE)
    }, add = TRUE)

    metadata <- data.frame(
        group = factor(
            ifelse(sim$group == 0, "control", "case"),
            levels = c("control", "case")
        ),
        z = sim$z[, 1L],
        log_depth = log(sim$depth),
        row.names = rownames(sim$counts)
    )

    arguments <- list(
        input_data = as.data.frame(
            sim$counts[, sim$truth$retained, drop = FALSE]
        ),
        input_metadata = metadata,
        output = output_dir,
        formula = "~ group + z + log_depth",
        min_abundance = 0,
        min_prevalence = 0,
        max_prevalence = 1.01,
        zero_threshold = 0,
        min_variance = 0,
        normalization = "TSS",
        transform = "LOG",
        correction = "BH",
        standardize = TRUE,
        median_comparison_abundance =
            isTRUE(config$maaslin3_median_comparison),
        median_comparison_prevalence = FALSE,
        warn_prevalence = FALSE,
        augment = TRUE,
        plot_summary_plot = FALSE,
        plot_associations = FALSE,
        max_pngs = 1,
        cores = 1,
        save_models = FALSE,
        save_plots_rds = FALSE,
        verbosity = "ERROR"
    )
    available_arguments <- names(formals(maaslin3::maaslin3))
    if ("evaluate_only" %in% available_arguments) {
        arguments$evaluate_only <- "abundance"
    }
    if ("subtract_median" %in% available_arguments) {
        arguments$subtract_median <- FALSE
    }
    arguments <- arguments[names(arguments) %in% available_arguments]

    warning_text <- character()
    set.seed(
        config$base_seed + rep_id * 10007L +
            match(scenario_name, SCENARIOS$scenario)
    )
    try(maaslin3::maaslin_log_reset(), silent = TRUE)
    fit <- tryCatch(
        {
            invisible(capture.output(
                fit_value <- withCallingHandlers(
                    suppressMessages(do.call(maaslin3::maaslin3, arguments)),
                    warning = function(w) {
                        warning_text <<- c(warning_text, conditionMessage(w))
                        invokeRestart("muffleWarning")
                    }
                )
            ))
            fit_value
        },
        error = function(e) e
    )

    if (inherits(fit, "error")) {
        return(empty_method_rows(
            target_names,
            "MaAsLin 3 abundance",
            paste0("error: ", conditionMessage(fit))
        ))
    }

    output <- extract_maaslin3_abundance(fit, target_names)
    global_warning <- collapse_conditions(warning_text)
    if (!is.na(global_warning)) output$warning <- global_warning
    output
}

# =============================================================================
# Microbiome data-generating mechanism
# =============================================================================

matched_group_vector <- function(values) {
    c(values, sample(values, length(values), replace = FALSE))
}

make_base_replication <- function(rep_id, dgp, config) {
    set.seed(
        config$base_seed + 10000L * rep_id +
            if (identical(dgp, "heavy_tail")) 700000L else 0L
    )

    n0 <- config$n_per_group
    n <- 2L * n0
    p <- config$n_taxa
    group <- c(rep(0, n0), rep(1, n0))

    # A measured covariate is moderately associated with group and affects both
    # structural absence and positive abundance.
    z <- config$covariate_group_shift * group + rnorm(n)

    # Depth is generated from the same empirical distribution in both groups.
    depth_reference <- round(exp(
        rnorm(n0, log(config$depth_median), config$depth_sdlog)
    ))
    depth_reference <- as.integer(clamp(
        depth_reference, config$depth_min, config$depth_max
    ))
    depth <- matched_group_vector(depth_reference)

    # Baseline absolute abundances span common to rare taxa.
    base_weight <- exp(seq(log(0.12), log(0.00035), length.out = p))
    base_weight <- base_weight / sum(base_weight)
    abundance_intercept <- log(base_weight)

    rho_intercept <- seq(qlogis(0.07), qlogis(0.38), length.out = p) +
        rnorm(p, 0, 0.10)
    rho_z_effect <- rnorm(p, 0, 0.12)
    abundance_z_effect <- rnorm(p, 0, 0.10)
    factor_loading <- rnorm(p, 0, config$loading_sd)
    abundance_sd <- runif(
        p, config$abundance_sd_min, config$abundance_sd_max
    )

    sample_factor <- rnorm(n, 0, config$sample_factor_sd)
    structural_uniform <- matrix(runif(n * p), nrow = n, ncol = p)
    if (identical(dgp, "heavy_tail")) {
        abundance_error <- matrix(
            rt(n * p, df = 4) / sqrt(2),
            nrow = n, ncol = p
        )
    } else {
        abundance_error <- matrix(rnorm(n * p), nrow = n, ncol = p)
    }

    taxa <- sprintf("Taxon_%03d", seq_len(p))
    samples <- sprintf("Sample_%03d", seq_len(n))

    list(
        group = group,
        z = z,
        depth = depth,
        abundance_intercept = abundance_intercept,
        rho_intercept = rho_intercept,
        rho_z_effect = rho_z_effect,
        abundance_z_effect = abundance_z_effect,
        factor_loading = factor_loading,
        abundance_sd = abundance_sd,
        sample_factor = sample_factor,
        structural_uniform = structural_uniform,
        abundance_error = abundance_error,
        taxa = taxa,
        samples = samples
    )
}

scenario_signal_vectors <- function(base, scenario, config) {
    p <- config$n_taxa
    abundance_effect <- numeric(p)
    structural_effect <- numeric(p)
    baseline_log_offset <- numeric(p)
    structural_log_odds_offset <- numeric(p)

    order_common_to_rare <- order(base$abundance_intercept, decreasing = TRUE)
    moderate <- order_common_to_rare[
        seq.int(4L, min(p - 6L, 15L))
    ]
    if (length(moderate) < 8L) moderate <- order_common_to_rare

    balanced_set <- moderate[seq_len(min(6L, length(moderate)))]
    if (length(balanced_set) %% 2L == 1L) {
        balanced_set <- balanced_set[-length(balanced_set)]
    }
    balanced_direction <- rep(c(1, -1), length.out = length(balanced_set))

    rare_set <- tail(order_common_to_rare, min(6L, p))
    if (length(rare_set) %% 2L == 1L) rare_set <- rare_set[-1L]
    rare_direction <- rep(c(1, -1), length.out = length(rare_set))

    sparse_set <- unique(round(seq(3, p - 3, length.out = min(4L, p - 4L))))
    dense_set <- order_common_to_rare[
        seq_len(max(4L, min(p - 4L, as.integer(round(0.40 * p)))))
    ]
    structural_candidates <- setdiff(
        order_common_to_rare,
        union(balanced_set, rare_set)
    )
    if (length(structural_candidates) < 4L) {
        structural_candidates <- order_common_to_rare
    }
    structural_set <- structural_candidates[seq_len(min(4L, p))]
    structural_direction <- rep(c(1, -1), length.out = length(structural_set))

    if (scenario == "balanced_abundance") {
        abundance_effect[balanced_set] <-
            config$balanced_abundance_effect * balanced_direction
    } else if (scenario == "rare_present_abundance") {
        abundance_effect[rare_set] <-
            config$rare_abundance_effect * rare_direction
        baseline_log_offset[rare_set] <-
            log(config$rare_baseline_multiplier)
        structural_log_odds_offset[rare_set] <-
            config$rare_structural_log_odds_offset
    } else if (scenario == "sparse_unidirectional") {
        abundance_effect[sparse_set] <-
            config$sparse_unidirectional_effect
    } else if (scenario == "dense_unidirectional") {
        abundance_effect[dense_set] <-
            config$dense_unidirectional_effect
    } else if (scenario == "structural_only") {
        structural_effect[structural_set] <-
            config$structural_log_odds_effect * structural_direction
    } else if (scenario == "mixed_structural_abundance") {
        abundance_effect[balanced_set] <-
            config$balanced_abundance_effect * balanced_direction
        structural_effect[structural_set] <-
            config$structural_log_odds_effect * structural_direction
    }

    list(
        abundance_effect = abundance_effect,
        structural_effect = structural_effect,
        baseline_log_offset = baseline_log_offset,
        structural_log_odds_offset = structural_log_odds_offset,
        balanced_set = balanced_set,
        rare_set = rare_set,
        sparse_set = sparse_set,
        dense_set = dense_set,
        structural_set = structural_set
    )
}

oracle_taxon_summary <- function(relative_abundance, counts, structural_absent,
                                 group, z, direct_effect) {
    p <- ncol(relative_abundance)
    rows <- vector("list", p)
    for (j in seq_len(p)) {
        present <- !structural_absent[, j]
        detected <- counts[, j] > 0

        latent_coefficient <- NA_real_
        if (sum(present) >= 8L &&
            length(unique(group[present])) == 2L) {
            latent_fit <- tryCatch(
                lm(
                    log(relative_abundance[present, j]) ~
                        group[present] + z[present]
                ),
                error = function(e) NULL
            )
            if (!is.null(latent_fit)) {
                latent_coefficient <- unname(coef(latent_fit)[2L])
            }
        }

        detected_coefficient <- NA_real_
        if (sum(detected) >= 8L &&
            length(unique(group[detected])) == 2L) {
            detected_fit <- tryCatch(
                lm(
                    log(counts[detected, j] /
                            rowSums(counts)[detected]) ~
                        group[detected] + z[detected]
                ),
                error = function(e) NULL
            )
            if (!is.null(detected_fit)) {
                detected_coefficient <- unname(coef(detected_fit)[2L])
            }
        }

        rows[[j]] <- data.frame(
            oracle_latent_log_relative_effect = latent_coefficient,
            oracle_detected_log_relative_effect = detected_coefficient,
            present_nondetection_reference = if (any(present & group == 0)) {
                mean(counts[present & group == 0, j] == 0)
            } else {
                NA_real_
            },
            present_nondetection_comparison = if (any(present & group == 1)) {
                mean(counts[present & group == 1, j] == 0)
            } else {
                NA_real_
            },
            direct_log_absolute_effect = direct_effect[j],
            stringsAsFactors = FALSE
        )
    }
    dplyr::bind_rows(rows)
}

simulate_scenario <- function(base, scenario, rep_id, dgp, config) {
    n <- length(base$group)
    p <- config$n_taxa
    signal <- scenario_signal_vectors(base, scenario, config)

    scenario_depth <- base$depth
    if (scenario == "depth_imbalanced_null") {
        comparison <- base$group == 1
        scenario_depth[comparison] <- as.integer(clamp(
            round(scenario_depth[comparison] *
                      config$depth_imbalance_multiplier),
            config$depth_min,
            config$depth_max
        ))
    }

    lp_rho <- matrix(
        base$rho_intercept + signal$structural_log_odds_offset,
        nrow = n, ncol = p, byrow = TRUE
    ) +
        outer(base$z, base$rho_z_effect) +
        outer(base$group, signal$structural_effect)
    rho <- plogis(lp_rho)
    structural_absent <- base$structural_uniform < rho

    scenario_abundance_intercept <-
        base$abundance_intercept + signal$baseline_log_offset
    log_absolute <- matrix(
        scenario_abundance_intercept, nrow = n, ncol = p, byrow = TRUE
    ) +
        outer(base$z, base$abundance_z_effect) +
        outer(base$sample_factor, base$factor_loading) +
        outer(base$group, signal$abundance_effect) +
        matrix(
            base$abundance_error, nrow = n, ncol = p
        ) * matrix(
            base$abundance_sd, nrow = n, ncol = p, byrow = TRUE
        )

    absolute_abundance <- exp(log_absolute)
    absolute_abundance[structural_absent] <- 0

    zero_rows <- which(rowSums(absolute_abundance) <= 0)
    if (length(zero_rows)) {
        anchor <- which.max(scenario_abundance_intercept)
        absolute_abundance[zero_rows, anchor] <-
            exp(scenario_abundance_intercept[anchor])
        structural_absent[zero_rows, anchor] <- FALSE
    }

    relative_abundance <- absolute_abundance / rowSums(absolute_abundance)

    set.seed(
        config$base_seed + 1000000L + 10000L * rep_id +
            100L * match(scenario, SCENARIOS$scenario) +
            if (identical(dgp, "heavy_tail")) 50L else 0L
    )
    count_by_sample <- t(vapply(seq_len(n), function(i) {
        as.numeric(rmultinom(
            1L, size = scenario_depth[i], prob = relative_abundance[i, ]
        )[, 1L])
    }, numeric(p)))

    rownames(count_by_sample) <- base$samples
    colnames(count_by_sample) <- base$taxa

    retained <- colSums(count_by_sample > 0) >= 3L
    oracle <- oracle_taxon_summary(
        relative_abundance = relative_abundance,
        counts = count_by_sample,
        structural_absent = structural_absent,
        group = base$group,
        z = base$z,
        direct_effect = signal$abundance_effect
    )

    truth <- data.frame(
        target = base$taxa,
        retained = retained,
        abundance_alt = signal$abundance_effect != 0,
        structural_alt = signal$structural_effect != 0,
        abundance_effect = signal$abundance_effect,
        structural_effect = signal$structural_effect,
        baseline_relative_abundance =
            exp(scenario_abundance_intercept) /
            sum(exp(scenario_abundance_intercept)),
        n_positive_reference =
            colSums(count_by_sample[base$group == 0, , drop = FALSE] > 0),
        n_positive_comparison =
            colSums(count_by_sample[base$group == 1, , drop = FALSE] > 0),
        stringsAsFactors = FALSE
    )
    truth <- cbind(truth, oracle)

    list(
        counts = count_by_sample,
        depth = scenario_depth,
        group = base$group,
        z = matrix(base$z, ncol = 1L),
        structural_absent = structural_absent,
        relative_abundance = relative_abundance,
        truth = truth
    )
}

# =============================================================================
# Per-scenario analysis and operating characteristics
# =============================================================================

apply_common_multiplicity <- function(method_results, truth, alpha) {
    merged <- dplyr::left_join(method_results, truth, by = "target")
    merged$p_for_family <- ifelse(
        merged$retained & merged$available & is.finite(merged$p_value),
        merged$p_value,
        ifelse(merged$retained, 1, NA_real_)
    )
    merged$q_bh <- NA_real_

    # Each method defines one multiplicity family over the same retained taxa.
    # P-values from different methods are never pooled in the same BH adjustment.
    for (method_name in unique(merged$method)) {
        family <- which(
            merged$method == method_name &
                merged$retained &
                is.finite(merged$p_for_family)
        )
        if (length(family)) {
            merged$q_bh[family] <- p.adjust(
                merged$p_for_family[family], method = "BH"
            )
        }
    }

    merged$reject_raw <- merged$retained &
        is.finite(merged$p_for_family) &
        merged$p_for_family <= alpha
    merged$reject_bh <- merged$retained &
        is.finite(merged$q_bh) &
        merged$q_bh <= alpha
    merged
}

method_metrics <- function(result, rep_id, dgp, scenario, alpha) {
    methods <- unique(result$method)
    rows <- vector("list", length(methods))

    for (m in seq_along(methods)) {
        method <- methods[m]
        data <- result[result$method == method & result$retained, , drop = FALSE]
        alt <- data$abundance_alt
        null <- !alt
        rejected <- data$reject_bh
        n_rejected <- sum(rejected)
        false <- sum(rejected & null)
        true <- sum(rejected & alt)

        rows[[m]] <- data.frame(
            replicate = rep_id,
            dgp = dgp,
            scenario = scenario,
            method = method,
            n_family = nrow(data),
            n_alt = sum(alt),
            n_available = sum(data$available),
            n_rejected = n_rejected,
            n_false = false,
            n_true = true,
            fdp = if (n_rejected > 0L) false / n_rejected else 0,
            any_false = as.integer(false > 0L),
            power = if (sum(alt) > 0L) true / sum(alt) else NA_real_,
            raw_type1 = if (sum(null) > 0L) {
                mean(data$reject_raw[null])
            } else {
                NA_real_
            },
            conditional_raw_type1 = if (any(null & data$available)) {
                mean(data$p_value[null & data$available] <= alpha)
            } else {
                NA_real_
            },
            availability = if (nrow(data) > 0L) {
                mean(data$available)
            } else {
                NA_real_
            },
            stringsAsFactors = FALSE
        )
    }
    dplyr::bind_rows(rows)
}

analyze_scenario <- function(sim, config, rep_id, dgp, scenario) {
    proposed <- run_proposed_method(sim, config)
    zinq <- run_zinq_abundance(sim, config, rep_id)
    maaslin3 <- run_maaslin3_abundance(
        sim, config, rep_id, scenario
    )

    all_results <- dplyr::bind_rows(proposed, zinq, maaslin3)
    all_results <- apply_common_multiplicity(
        all_results, sim$truth, config$alpha
    )
    all_results$replicate <- rep_id
    all_results$dgp <- dgp
    all_results$scenario <- scenario

    list(
        raw = all_results,
        metrics = method_metrics(
            all_results, rep_id, dgp, scenario, config$alpha
        ),
        truth = transform(
            sim$truth,
            replicate = rep_id,
            dgp = dgp,
            scenario = scenario
        )
    )
}

run_replicate <- function(rep_id, config, run_signature) {
    checkpoint_file <- file.path(
        checkpoint_dir, sprintf("replicate_%04d.rds", rep_id)
    )
    if (isTRUE(config$resume) && file.exists(checkpoint_file)) {
        saved <- tryCatch(readRDS(checkpoint_file), error = function(e) NULL)
        if (!is.null(saved) &&
            identical(saved$run_signature, run_signature) &&
            isTRUE(saved$success)) {
            return(saved)
        }
    }

    result <- tryCatch({
        raw_list <- list()
        metric_list <- list()
        truth_list <- list()
        index <- 0L

        for (dgp in DGP_VARIANTS) {
            base <- make_base_replication(rep_id, dgp, config)
            for (scenario in SCENARIOS$scenario) {
                sim <- simulate_scenario(
                    base, scenario, rep_id, dgp, config
                )
                analyzed <- analyze_scenario(
                    sim, config, rep_id, dgp, scenario
                )
                index <- index + 1L
                raw_list[[index]] <- analyzed$raw
                metric_list[[index]] <- analyzed$metrics
                truth_list[[index]] <- analyzed$truth
            }
        }

        list(
            success = TRUE,
            replicate = rep_id,
            run_signature = run_signature,
            raw = dplyr::bind_rows(raw_list),
            metrics = dplyr::bind_rows(metric_list),
            truth = dplyr::bind_rows(truth_list),
            error = NA_character_
        )
    }, error = function(e) {
        list(
            success = FALSE,
            replicate = rep_id,
            run_signature = run_signature,
            raw = NULL,
            metrics = NULL,
            truth = NULL,
            error = conditionMessage(e)
        )
    })

    temporary <- paste0(
        checkpoint_file, ".tmp_", Sys.getpid(), "_",
        sample.int(1e8, 1L)
    )
    saveRDS(result, temporary)
    if (!file.rename(temporary, checkpoint_file)) {
        unlink(temporary)
        stop("Could not write checkpoint ", checkpoint_file, ".", call. = FALSE)
    }
    result
}

# =============================================================================
# Summaries, figures and output
# =============================================================================

summarize_metrics <- function(metrics) {
    metrics %>%
        group_by(dgp, scenario, method) %>%
        summarise(
            n_rep = n(),
            empirical_fdr = mean(fdp),
            mcse_fdr = safe_sd(fdp) / sqrt(n()),
            fdr_lower = pmax(0, empirical_fdr - 1.96 * mcse_fdr),
            fdr_upper = pmin(1, empirical_fdr + 1.96 * mcse_fdr),
            marginal_fwer = mean(any_false),
            mFDR = sum(n_false) / max(sum(n_rejected), 1),
            power = safe_mean(power),
            mcse_power = safe_sd(power) /
                sqrt(max(sum(is.finite(power)), 1)),
            power_lower = pmax(0, power - 1.96 * mcse_power),
            power_upper = pmin(1, power + 1.96 * mcse_power),
            raw_type1 = safe_mean(raw_type1),
            mcse_raw_type1 = safe_sd(raw_type1) /
                sqrt(max(sum(is.finite(raw_type1)), 1)),
            conditional_raw_type1 = safe_mean(conditional_raw_type1),
            availability = safe_mean(availability),
            mean_discoveries = mean(n_rejected),
            mean_false_discoveries = mean(n_false),
            .groups = "drop"
        )
}

publication_theme <- function() {
    theme_classic(base_size = 12) +
        theme(
            legend.position = "top",
            axis.text.x = element_text(angle = 28, hjust = 1),
            strip.background = element_blank(),
            strip.text = element_text(size = 10),
            plot.margin = margin(8, 12, 8, 8)
        )
}

save_publication_plot <- function(plot, stem, output_dir,
                                  width = 10, height = 6) {
    pdf_device <- if (isTRUE(capabilities("cairo"))) {
        grDevices::cairo_pdf
    } else {
        "pdf"
    }
    ggsave(
        file.path(output_dir, paste0(stem, ".pdf")),
        plot = plot, width = width, height = height,
        units = "in", device = pdf_device
    )
    ggsave(
        file.path(output_dir, paste0(stem, ".png")),
        plot = plot, width = width, height = height,
        units = "in", dpi = 600
    )
}

make_plots <- function(summary, raw, output_dir, alpha) {
    scenario_order <- SCENARIOS$scenario
    scenario_labels <- setNames(SCENARIOS$label, SCENARIOS$scenario)

    plot_summary <- summary %>%
        mutate(
            scenario_label = factor(
                scenario_labels[scenario],
                levels = scenario_labels[scenario_order]
            )
        )

    fdr_plot <- ggplot(
        plot_summary,
        aes(
            x = scenario_label,
            y = empirical_fdr,
            group = method,
            linetype = method,
            shape = method
        )
    ) +
        geom_hline(yintercept = alpha, linetype = 3) +
        geom_errorbar(
            aes(ymin = fdr_lower, ymax = fdr_upper),
            width = 0.10,
            position = position_dodge(width = 0.22)
        ) +
        geom_line(position = position_dodge(width = 0.22)) +
        geom_point(size = 2.3, position = position_dodge(width = 0.22)) +
        facet_wrap(~ dgp) +
        labs(
            x = NULL,
            y = "FDR relative to directly perturbed taxa",
            linetype = NULL,
            shape = NULL
        ) +
        publication_theme()
    save_publication_plot(
        fdr_plot, "fig_abundance_fdr", output_dir, 11, 6
    )

    type1_plot <- ggplot(
        plot_summary,
        aes(
            x = scenario_label,
            y = raw_type1,
            group = method,
            linetype = method,
            shape = method
        )
    ) +
        geom_hline(yintercept = alpha, linetype = 3) +
        geom_line(position = position_dodge(width = 0.22)) +
        geom_point(size = 2.3, position = position_dodge(width = 0.22)) +
        facet_wrap(~ dgp) +
        labs(
            x = NULL,
            y = "Rejection rate among non-perturbed taxa",
            linetype = NULL,
            shape = NULL
        ) +
        publication_theme()
    save_publication_plot(
        type1_plot, "fig_abundance_type1", output_dir, 11, 6
    )

    power_data <- plot_summary %>% filter(is.finite(power))
    power_plot <- ggplot(
        power_data,
        aes(
            x = scenario_label,
            y = power,
            group = method,
            linetype = method,
            shape = method
        )
    ) +
        geom_errorbar(
            aes(ymin = power_lower, ymax = power_upper),
            width = 0.10,
            position = position_dodge(width = 0.22)
        ) +
        geom_line(position = position_dodge(width = 0.22)) +
        geom_point(size = 2.3, position = position_dodge(width = 0.22)) +
        facet_wrap(~ dgp) +
        coord_cartesian(ylim = c(0, 1)) +
        labs(
            x = NULL,
            y = "Abundance power",
            linetype = NULL,
            shape = NULL
        ) +
        publication_theme()
    save_publication_plot(
        power_plot, "fig_abundance_power", output_dir, 11, 6
    )

    availability_plot <- ggplot(
        plot_summary,
        aes(
            x = scenario_label,
            y = availability,
            group = method,
            linetype = method,
            shape = method
        )
    ) +
        geom_line(position = position_dodge(width = 0.22)) +
        geom_point(size = 2.3, position = position_dodge(width = 0.22)) +
        facet_wrap(~ dgp) +
        coord_cartesian(ylim = c(0, 1)) +
        labs(
            x = NULL,
            y = "Proportion of abundance tests available",
            linetype = NULL,
            shape = NULL
        ) +
        publication_theme()
    save_publication_plot(
        availability_plot, "fig_abundance_availability", output_dir, 11, 6
    )

    qq_data <- raw %>%
        filter(
            scenario == "global_null",
            available,
            is.finite(p_value)
        ) %>%
        group_by(dgp, method) %>%
        arrange(p_value, .by_group = TRUE) %>%
        mutate(expected = (row_number() - 0.5) / n()) %>%
        ungroup()

    qq_plot <- ggplot(
        qq_data,
        aes(x = expected, y = p_value)
    ) +
        geom_abline(intercept = 0, slope = 1, linetype = 3) +
        geom_point(alpha = 0.35, size = 0.7) +
        facet_grid(dgp ~ method) +
        coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +
        labs(
            x = "Expected uniform quantile",
            y = "Observed abundance p-value"
        ) +
        theme_classic(base_size = 11)
    save_publication_plot(
        qq_plot, "fig_abundance_global_null_qq", output_dir, 11, 6
    )
}

write_method_settings <- function(output_dir) {
    settings <- data.frame(
        method = c(
            "DASRA proposed abundance",
            "ZINQ quantile abundance",
            "MaAsLin 3 abundance"
        ),
        implementation = c(
            paste0(
                "Stacked positive-mark, structural-nuisance and posterior ",
                "abundance estimating equations; mean-log-relative effect; ",
                "target-excluded robust reference correction; joint influence variance"
            ),
            paste0(
                "ZINQ::ZINQ_tests quantile component on TSS relative ",
                "abundances; taus = ",
                paste(CONFIG$zinq_taus, collapse = ", "),
                "; quantile p-values combined by a Cauchy test"
            ),
            paste0(
                "maaslin3::maaslin3 abundance model; TSS, LOG, ",
                "standardize = TRUE, median_comparison_abundance = ",
                CONFIG$maaslin3_median_comparison,
                ", evaluate_only = abundance when supported"
            )
        ),
        zero_handling = c(
            "Zeros enter the finite-depth count likelihood",
            "Abundance quantiles use detected observations",
            "Linear abundance model uses detected observations"
        ),
        multiplicity = "BH recomputed over the common retained-taxon family",
        stringsAsFactors = FALSE
    )
    write.csv(
        settings,
        file.path(output_dir, "method_settings.csv"),
        row.names = FALSE
    )
}

# =============================================================================
# Main
# =============================================================================

main <- function() {
    if (.Platform$OS.type == "windows" && CONFIG$n_cores > 1L) {
        stop(
            "This script uses parallel::mclapply on macOS/Linux. ",
            "Set DASRA_ABUND_CORES=1 on Windows.",
            call. = FALSE
        )
    }

    software_versions <- vapply(required_packages, function(package) {
        as.character(utils::packageVersion(package))
    }, character(1))

    design_config <- CONFIG
    design_config$n_rep <- NULL
    design_config$n_cores <- NULL
    design_config$output_dir <- NULL
    design_config$resume <- NULL

    design_record <- list(
        design = design_config,
        scenarios = SCENARIOS,
        dgp_variants = DGP_VARIANTS,
        software_versions = software_versions,
        script_fingerprint = script_fingerprint(),
        R = R.version.string,
        platform = R.version$platform
    )
    run_signature <- object_fingerprint(design_record)

    design_path <- file.path(
        CONFIG$output_dir, "simulation_design_config.rds"
    )
    if (file.exists(design_path)) {
        previous <- readRDS(design_path)
        if (!identical(previous, design_record)) {
            stop(
                "The output directory contains checkpoints from a different ",
                "design, software environment or script version. Choose a ",
                "new DASRA_ABUND_OUTDIR.",
                call. = FALSE
            )
        }
    } else {
        saveRDS(design_record, design_path)
    }

    write_method_settings(CONFIG$output_dir)

    message("DASRA present-conditional abundance simulation")
    message("  Replications: ", CONFIG$n_rep)
    message("  Samples per group: ", CONFIG$n_per_group)
    message("  Taxa: ", CONFIG$n_taxa)
    message("  DGP variants: ", paste(DGP_VARIANTS, collapse = ", "))
    message("  Scenarios: ", paste(SCENARIOS$scenario, collapse = ", "))
    message("  Workers: ", CONFIG$n_cores)
    message("  Quadrature order: ", CONFIG$quadrature_order)
    message("  Output: ", normalizePath(
        CONFIG$output_dir, winslash = "/", mustWork = FALSE
    ))

    replicate_ids <- seq_len(CONFIG$n_rep)
    if (.Platform$OS.type == "unix" && CONFIG$n_cores > 1L) {
        replicate_results <- parallel::mclapply(
            replicate_ids,
            run_replicate,
            config = CONFIG,
            run_signature = run_signature,
            mc.cores = CONFIG$n_cores,
            mc.preschedule = FALSE,
            mc.set.seed = FALSE
        )
    } else {
        replicate_results <- lapply(
            replicate_ids,
            run_replicate,
            config = CONFIG,
            run_signature = run_signature
        )
    }

    successful <- vapply(
        replicate_results, function(x) isTRUE(x$success), logical(1)
    )
    if (!all(successful)) {
        failures <- data.frame(
            replicate = replicate_ids[!successful],
            error = vapply(
                replicate_results[!successful],
                function(x) x$error %||% "unknown error",
                character(1)
            )
        )
        write.csv(
            failures,
            file.path(CONFIG$output_dir, "replicate_failures.csv"),
            row.names = FALSE
        )
        warning(sum(!successful), " replicate(s) failed.")
    }
    if (!any(successful)) {
        stop("No replicate completed successfully.", call. = FALSE)
    }

    replicate_results <- replicate_results[successful]
    raw <- dplyr::bind_rows(lapply(replicate_results, `[[`, "raw"))
    metrics <- dplyr::bind_rows(lapply(replicate_results, `[[`, "metrics"))
    truth <- dplyr::bind_rows(lapply(replicate_results, `[[`, "truth"))
    summary <- summarize_metrics(metrics)

    write.csv(
        raw,
        file.path(CONFIG$output_dir, "combined_taxon_method_results.csv"),
        row.names = FALSE
    )
    write.csv(
        metrics,
        file.path(CONFIG$output_dir, "combined_replicate_metrics.csv"),
        row.names = FALSE
    )
    write.csv(
        summary,
        file.path(CONFIG$output_dir, "combined_power_type1_fdr_summary.csv"),
        row.names = FALSE
    )
    write.csv(
        truth,
        file.path(CONFIG$output_dir, "combined_simulation_truth.csv"),
        row.names = FALSE
    )
    write.csv(
        SCENARIOS,
        file.path(CONFIG$output_dir, "simulation_scenarios.csv"),
        row.names = FALSE
    )

    truth_summary <- truth %>%
        group_by(dgp, scenario, abundance_alt) %>%
        summarise(
            n_taxon_replications = n(),
            mean_baseline_relative_abundance =
                mean(baseline_relative_abundance),
            mean_positive_reference = mean(n_positive_reference),
            mean_positive_comparison = mean(n_positive_comparison),
            mean_present_nondetection_reference =
                safe_mean(present_nondetection_reference),
            mean_present_nondetection_comparison =
                safe_mean(present_nondetection_comparison),
            mean_oracle_latent_effect =
                safe_mean(oracle_latent_log_relative_effect),
            mean_oracle_detected_effect =
                safe_mean(oracle_detected_log_relative_effect),
            .groups = "drop"
        )
    write.csv(
        truth_summary,
        file.path(CONFIG$output_dir, "simulation_truth_summary.csv"),
        row.names = FALSE
    )

    status_summary <- raw %>%
        count(dgp, scenario, method, available, status, name = "n")
    write.csv(
        status_summary,
        file.path(CONFIG$output_dir, "method_status_summary.csv"),
        row.names = FALSE
    )

    make_plots(
        summary = summary,
        raw = raw,
        output_dir = CONFIG$output_dir,
        alpha = CONFIG$alpha
    )

    session_lines <- c(
        "DASRA present-conditional abundance simulation",
        paste0("Run date: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
        "",
        "Configuration:",
        capture.output(str(CONFIG)),
        "",
        "Scenarios:",
        capture.output(print(SCENARIOS)),
        "",
        "Package versions:",
        paste0(names(software_versions), ": ", software_versions),
        "",
        "Script fingerprint:",
        as.character(design_record$script_fingerprint),
        "",
        "Session information:",
        capture.output(sessionInfo())
    )
    writeLines(
        session_lines,
        file.path(CONFIG$output_dir, "session_information.txt")
    )

    message("Simulation complete.")
    message("Key outputs:")
    message("  combined_power_type1_fdr_summary.csv")
    message("  combined_replicate_metrics.csv")
    message("  combined_taxon_method_results.csv")
    message("  combined_simulation_truth.csv")
    message("  simulation_truth_summary.csv")
    message("  method_status_summary.csv")
    message("  fig_abundance_fdr.pdf")
    message("  fig_abundance_type1.pdf")
    message("  fig_abundance_power.pdf")
    message("  fig_abundance_availability.pdf")
    message("  fig_abundance_global_null_qq.pdf")
}

main()
