# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doram_gk15_panel_cpp <- function(a, b, y, N, eta, sigma, mode, p_mode, mode_residual) {
    .Call(`_DORAM_doram_gk15_panel_cpp`, a, b, y, N, eta, sigma, mode, p_mode, mode_residual)
}

doram_integrate_moments_cpp <- function(y, N, eta, sigma, mode, p_mode, mode_residual, local_scale, relative_tolerance, radius, maximum_panels, tail_error) {
    .Call(`_DORAM_doram_integrate_moments_cpp`, y, N, eta, sigma, mode, p_mode, mode_residual, local_scale, relative_tolerance, radius, maximum_panels, tail_error)
}

